<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/ad_lib.php';require_once __DIR__.'/square_lib.php';tt_require_login();$db=tt_db_open(false);tt_ad_require_schema($db);$uid=(int)$_SESSION['id'];$bal=tt_ad_credit_balances($db,$uid);$paidReady=tt_ad_paid_schema_ready($db);$squareReady=$paidReady&&tt_square_ready();$pending=[];if($paidReady){$s=tt_prepare($db,'SELECT `id`,`amount_cents`,`credits`,`status`,`created_at`,`paid_at` FROM `square_ad_purchases` WHERE `account_id`=? ORDER BY `id` DESC LIMIT 20');$s->bind_param('i',$uid);$s->execute();$pending=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();}$db->close();
?><!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Ads</title></head><body><?php tt_nav('adcredits.php');?><main class="content"><h2>Ads & impressions</h2><?php if(isset($_GET['square_return'])):?><p class="notice ok">Returned from Square. Funded impressions appear after Square confirms the completed payment by webhook; refresh if confirmation is still arriving.</p><?php endif;?>
<section class="grid"><article class="card"><h3>Natural ad balance</h3><p><strong><?=number_format($bal['natural'])?> natural credits</strong> = <?=number_format($bal['natural'])?> impressions.</p><p>Natural credits are earned when another user's counted ad impression is hosted on your page and are spent when you boost your own post. <strong>1 natural credit = 1 counted impression.</strong></p></article><article class="card"><h3>Square-funded impressions</h3><p><strong><?=number_format($bal['paid'])?> funded impressions</strong> are available from completed Square purchases.</p><p class="meta">They are kept separate from natural credits internally so Square-funded display earnings can be accounted for exactly.</p></article><article class="card"><h3>Buy 1,000 SFW impressions — $5</h3><p>$5 funds <strong>1,000 counted impressions</strong>. For qualifying impressions displayed over another user's page/profile, <strong>4/5 of ad revenue</strong> accrues to that display subject and <strong>1/5</strong> to Tabletime.</p><?php if(!$paidReady):?><p class="notice">Run the protected schema migration once to enable Square-funded impressions and Earnings.</p><?php elseif(!$squareReady):?><p class="notice">Square production checkout still needs its host environment values.</p><?php else:?><form method="post" action="square_checkout.php"><input type="hidden" name="csrf" value="<?=tt_h(tt_ad_csrf())?>"><button type="submit">Buy 1,000 impressions for $5 with Square</button></form><p class="meta">Square environment: <?=tt_h(tt_square_env())?></p><?php endif;?></article></section>
<section class="card"><h3>Earn, spend, and cash earnings</h3><p>Boosting uses your available impression balance. Natural impressions stay non-cash. Square-funded impressions can create cash display-over earnings under the 4/5 subject · 1/5 Tabletime split. Your own ad shown on your own page is not counted as a payable display-over impression.</p><p>NSFW/mature advertising can use natural credits when correctly gated. Square-funded advertising is SFW-only.</p><p><a href="earnings.php">Open Earnings & payouts →</a> · <a href="square_setup.php">Set up your Square payout account →</a></p></section>
<?php if($pending):?><section class="card"><h3>Square impression purchases</h3><?php foreach($pending as $r):?><p>#<?=(int)$r['id']?> · $<?=number_format(((int)$r['amount_cents'])/100,2)?> · <?=number_format((int)$r['credits'])?> impressions · <strong><?=tt_h((string)$r['status'])?></strong> · <?=tt_h((string)$r['created_at'])?></p><?php endforeach;?></section><?php endif;?></main>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>
