<?php
header('Cache-Control: no-store, private, max-age=0');header('Pragma: no-cache');
require_once __DIR__.'/db.php';require_once __DIR__.'/maintenance.php';require_once __DIR__.'/schema_compat.php';require_once __DIR__.'/session_bootstrap.php';require_once __DIR__.'/age_gate_session.php';require_once __DIR__.'/social_controls.php';
function tt_login_fail(string $message,int $status=400):void{http_response_code($status);echo '<!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Login</title></head><body><main class="content"><h1><a href="/">TABLETIME</a></h1><section class="card"><h2>Login</h2><p>'.htmlspecialchars($message,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p><p><a href="login.php">Back to login</a> · <a href="setup.php">Database setup</a> · <a href="/">Home</a></p></section></main>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>';exit;}
if($_SERVER['REQUEST_METHOD']!=='POST'||!isset($_POST['submit'])){header('Location: login.php');exit;}if((string)($_POST['age18']??'')!=='1')tt_login_fail('Confirm that you are 18 or older to continue.');
$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');if($username===''||$password==='')tt_login_fail('Please fill both fields.');
if(!$TT_DB_CONFIGURED||!class_exists('mysqli'))tt_login_fail('The database runtime is not available.',503);$con=@new mysqli($DATABASE_HOST,$DATABASE_USER,$DATABASE_PASS,$DATABASE_NAME);if($con->connect_errno)tt_login_fail('Tabletime could not connect to MySQL.',503);$con->set_charset('utf8mb4');$missing=tt_verify_accounts_runtime_columns($con);if($missing){if((string)getenv('TABLETIME_ALLOW_RUNTIME_SCHEMA_UPGRADE')==='1'){$notes=[];if(!tt_upgrade_runtime_schema($con,$notes)){$con->close();tt_login_fail('The accounts schema needs maintenance. Open Database setup.',503);}$missing=tt_verify_accounts_runtime_columns($con);}if($missing){$con->close();tt_login_fail('The accounts schema is missing required columns. Run Database setup/maintenance once.',503);}}
$sql='SELECT `id`,`username`,`password`,`email`,`friends`,`posts`,`groups`,`events`,`colors`,`votes`,`forums`,`tags`,`aboutcontent`,`files` FROM `accounts` WHERE `username`=? LIMIT 1';$stmt=$con->prepare($sql);if(!$stmt){$e=$con->error;$con->close();tt_login_fail('Account query failed: '.$e,503);}$stmt->bind_param('s',$username);if(!$stmt->execute()){$e=$stmt->error;$stmt->close();$con->close();tt_login_fail('Account read failed: '.$e,503);}$row=$stmt->get_result()?->fetch_assoc();$aid=$row?(int)$row['id']:null;
$status=tt_delay_status($con,'login',$aid);if(!$status['allowed']){$stmt->close();$con->close();$left=$status['infinite']?'∞':tt_delay_human((int)$status['remaining']);tt_login_fail('Login timing lock active for '.$left.'. Login base delay is 10 minutes; failed attempts double it and Karma/Moksha can move the vote/voteban formula toward ∞.',429);}
if((int)($_POST['test']??-1)!==((int)($_POST['no1']??0)+(int)($_POST['no2']??0))){tt_delay_mark_failure($con,'login',$aid);$next=tt_delay_status($con,'login',$aid);$stmt->close();$con->close();tt_login_fail('Invalid captcha. Failed attempts double the login lock; current interval is '.tt_delay_human($next['duration']).'.');}
if(!$row||!password_verify($password,(string)$row['password'])){tt_delay_mark_failure($con,'login',$aid);$next=tt_delay_status($con,'login',$aid);$stmt->close();$con->close();tt_login_fail('Incorrect username and/or password. Failed attempts double the login lock; current interval is '.tt_delay_human($next['duration']).'.');}
$_SESSION['loggedin']=true;$_SESSION['id']=(int)$row['id'];$_SESSION['name']=(string)$row['username'];$_SESSION['tt_auth_hash']=(string)$row['password'];foreach(['friends','posts','groups','events','colors','votes','forums','tags','aboutcontent','files'] as $k)$_SESSION[$k]=$row[$k]??'';$uid=(int)$row['id'];tt_delay_mark_success($con,'login',$uid);tt_age_mark_passed($con,$uid);tt_auth_cookie_issue($uid,(string)$row['password']);$con->query('UPDATE `accounts` SET `last_login_at`=UTC_TIMESTAMP() WHERE `id`='.$uid);try{tt_opportunistic_maintenance($con);}catch(Throwable $e){}$stmt->close();$con->close();$ttReturn=tt_age_safe_return((string)($_POST['return']??''),'home.php');$ttTicket=tt_login_handoff_build($uid,(string)$row['password'],120);
$ttNext=$ttReturn;
if($ttTicket!==''){
    $frag='';$hashPos=strpos($ttNext,'#');if($hashPos!==false){$frag=substr($ttNext,$hashPos);$ttNext=substr($ttNext,0,$hashPos);}
    $ttNext.=(str_contains($ttNext,'?')?'&':'?').'tt_login='.rawurlencode($ttTicket).$frag;
}if(session_status()===PHP_SESSION_ACTIVE)@session_write_close();header('Cache-Control: private, no-store, max-age=0, must-revalidate');header('Pragma: no-cache');header('Vary: Cookie',false);header('Referrer-Policy: no-referrer');$safe=htmlspecialchars($ttNext,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$js=json_encode($ttNext,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_SLASHES);echo '<!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url='.$safe.'"><link rel="stylesheet" href="style.php"><title>Tabletime · Signed in</title></head><body><main class="content"><section class="card"><h2>Signed in</h2><p>Credentials accepted. Opening Tabletime…</p><p><a href="'.$safe.'">Continue</a></p></section></main><script>location.replace('.$js.');</script></body></html>';exit;
?>
