<?php
require_once dirname(__DIR__).'/core.php';header('Content-Type: application/json; charset=utf-8');tt_require_login();$db=tt_db_open(true);$uid=(int)$_SESSION['id'];$me=(string)$_SESSION['name'];$action=(string)($_REQUEST['action']??'');
function out($v,int $code=200){http_response_code($code);echo json_encode($v,JSON_UNESCAPED_SLASHES);exit;}
function getcall(mysqli $db,string $key){$q=$db->prepare('SELECT `id`,`scope_type`,`scope_id`,`created_by`,`title`,`members`,`status` FROM `calls` WHERE `call_key`=? LIMIT 1');$q->bind_param('s',$key);$q->execute();$r=$q->get_result()?->fetch_assoc();$q->close();return $r;}
function allowed(array $c,string $me):bool{return in_array($me,tt_member_list((string)$c['members']),true);}
try{
 if($action==='create'){ $delay=tt_delay_status($db,'call',$uid);if(!$delay['allowed'])out(['error'=>$delay['infinite']?'Call creation is locked at ∞ by Karma/Moksha/voteban balance.':'Call creation is timing-locked for another '.tt_delay_human((int)$delay['remaining']).'.','retry_after'=>$delay['remaining'],'delay'=>$delay],429);$scope=(string)($_POST['scope_type']??'private');if(!in_array($scope,['private','group','event'],true))out(['error'=>'invalid scope'],400);$sid=(int)($_POST['scope_id']??0);$title=substr(trim((string)($_POST['title']??'Tabletime call')),0,255);$members=tt_scope_members($db,$scope,$sid?:null,(string)($_POST['members']??''));if(!in_array($me,$members,true))$members[]=$me;$ids=tt_user_ids($db,$members);if(count($ids)<($scope==='private'?2:1))out(['error'=>'No valid call members were found.'],400);$key=bin2hex(random_bytes(16));$ms=tt_member_string(array_keys($ids));$sidv=$sid?:null;$q=$db->prepare('INSERT INTO `calls` (`call_key`,`scope_type`,`scope_id`,`created_by`,`title`,`members`) VALUES (?,?,?,?,?,?)');$q->bind_param('ssiiss',$key,$scope,$sidv,$uid,$title,$ms);$q->execute();$callId=(int)$db->insert_id;$q->close();foreach($ids as $name=>$id){if($id!==$uid)tt_notify($db,$id,'call','Incoming '.$scope.' call',$me.' invited you to '.$title,'calls.php?join='.$key);}tt_delay_mark_success($db,'call',$uid);out(['ok'=>true,'call_key'=>$key,'members'=>$ids,'title'=>$title]);}
 $key=(string)($_REQUEST['call_key']??'');if(!preg_match('/^[a-f0-9]{32}$/',$key))out(['error'=>'invalid call'],400);$c=getcall($db,$key);if(!$c||$c['status']!=='open'||!allowed($c,$me))out(['error'=>'call unavailable'],403);$cid=(int)$c['id'];
 if($action==='join'||$action==='heartbeat'){$q=$db->prepare('INSERT INTO `call_participants` (`call_id`,`account_id`,`username`,`joined_at`,`last_seen_at`,`left_at`) VALUES (?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP(),NULL) ON DUPLICATE KEY UPDATE `username`=VALUES(`username`),`last_seen_at`=UTC_TIMESTAMP(),`left_at`=NULL');$q->bind_param('iis',$cid,$uid,$me);$q->execute();$q->close();$db->query('UPDATE `calls` SET `updated_at`=UTC_TIMESTAMP() WHERE `id`='.$cid);$r=$db->query('SELECT `account_id`,`username` FROM `call_participants` WHERE `call_id`='.$cid.' AND `left_at` IS NULL AND `last_seen_at`>UTC_TIMESTAMP()-INTERVAL 45 SECOND');$peers=[];while($r&&$x=$r->fetch_assoc())$peers[]=['id'=>(int)$x['account_id'],'username'=>$x['username']];if($r)$r->free();out(['ok'=>true,'call'=>['title'=>$c['title'],'scope_type'=>$c['scope_type']],'peers'=>$peers]);}
 if($action==='signal'){$to=(int)($_POST['to']??0);$type=(string)($_POST['signal_type']??'');$payload=(string)($_POST['payload']??'');if(!in_array($type,['offer','answer','ice','renegotiate'],true)||strlen($payload)>131072)out(['error'=>'invalid signal'],400);$toV=$to?:null;$q=$db->prepare('INSERT INTO `call_signals` (`call_id`,`from_account_id`,`to_account_id`,`signal_type`,`payload`) VALUES (?,?,?,?,?)');$q->bind_param('iiiss',$cid,$uid,$toV,$type,$payload);$q->execute();$q->close();out(['ok'=>true]);}
 if($action==='poll'){$after=max(0,(int)($_GET['after']??0));$q=$db->prepare('SELECT s.`id`,s.`from_account_id`,a.`username`,s.`signal_type`,s.`payload` FROM `call_signals` s JOIN `accounts` a ON a.`id`=s.`from_account_id` WHERE s.`call_id`=? AND s.`id`>? AND s.`from_account_id`<>? AND (s.`to_account_id` IS NULL OR s.`to_account_id`=?) ORDER BY s.`id` ASC LIMIT 200');$q->bind_param('iiii',$cid,$after,$uid,$uid);$q->execute();$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);$q->close();out(['ok'=>true,'signals'=>$rows]);}
 if($action==='leave'){$q=$db->prepare('UPDATE `call_participants` SET `left_at`=UTC_TIMESTAMP() WHERE `call_id`=? AND `account_id`=?');$q->bind_param('ii',$cid,$uid);$q->execute();$q->close();out(['ok'=>true]);}
 out(['error'=>'unknown action'],400);
}catch(Throwable $e){out(['error'=>'Call service error','detail'=>$e->getMessage()],500);}finally{$db->close();}
?>