<?php
require_once __DIR__.'/core.php';tt_require_login();$db=tt_db_open(true);$me=(string)$_SESSION['name'];$uid=(int)$_SESSION['id'];
$groups=[];$events=[];$forums=[];$tags=[];
$r=$db->query('SELECT `id`,`title`,`members` FROM `groups` ORDER BY `title`');if($r){while($x=$r->fetch_assoc())if(in_array($me,tt_member_list((string)$x['members']),true))$groups[]=$x;$r->free();}
$r=$db->query('SELECT `id`,`title`,`members` FROM `events` ORDER BY `title`');if($r){while($x=$r->fetch_assoc())if(in_array($me,tt_member_list((string)$x['members']),true))$events[]=$x;$r->free();}
$r=$db->query('SELECT `id`,`tag` FROM `forums` ORDER BY `tag` LIMIT 200');if($r){while($x=$r->fetch_assoc())$forums[]=['id'=>(int)$x['id'],'title'=>(string)$x['tag']];$r->free();}
$r=$db->query('SELECT `value` FROM `tags` ORDER BY `value` LIMIT 200');if($r){while($x=$r->fetch_assoc())$tags[]=['id'=>0,'title'=>(string)$x['value']];$r->free();}$db->close();
$pref=trim((string)($_GET['scope']??'default'));if(!in_array($pref,['default','private','group','event','forum','tag'],true))$pref='default';
?><!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Calls</title></head><body><?php tt_nav('calls.php');?><main class="content"><section class="card"><h2>Calls</h2><p>Start an ad-hoc, private, Group, Event, Forum or Tag call. A blank/default call is valid and starts as your own broadcast room. You can participate in up to three calls at once, with up to 86 participants in each room. Starting the same target reuses the existing active room by default.</p><p class="meta">Direct WebRTC is used first. TURN remains optional fallback. Open a call in its dedicated call window to keep camera/audio running while browsing Tabletime.</p><form id="call-create"><label>Call type</label><select id="call-scope" name="scope_type"><?php foreach(['default'=>'Ad-hoc / broadcast','private'=>'Private','group'=>'Group','event'=>'Event','forum'=>'Forum','tag'=>'Tag'] as $v=>$l):?><option value="<?=$v?>" <?=$pref===$v?'selected':''?>><?=tt_h($l)?></option><?php endforeach;?></select><label id="private-label">People (semicolon separated usernames)</label><input id="call-members" name="members" type="text" placeholder="friend1;friend2"><label id="scope-label" hidden>Scope</label><select id="call-scope-id" name="scope_id" hidden></select><input id="call-scope-ref" name="scope_ref" type="hidden"><label>Call title</label><input id="call-title" name="title" type="text" maxlength="255" value="Tabletime call"><button type="submit">Create call</button></form><div id="call-status" class="notice" hidden></div></section><section id="my-calls" class="card"><h2>My active / incoming calls</h2><div id="call-dashboard"><p class="meta">Loading calls…</p></div></section><section id="call-room" class="card" hidden><h2 id="call-heading">Call</h2><p>Safari and iPhone require camera/microphone permission from a direct tap. Use Join / enable camera.</p><div class="actions"><button id="call-join" type="button">Join / enable camera</button><button id="call-camera" type="button" disabled>Camera on/off</button><button id="call-mic" type="button" disabled>Mic on/off</button><button id="call-share" type="button" disabled>Share screen</button><button id="call-leave" type="button" disabled>Leave</button></div><div class="video-grid"><figure><video id="local-video" autoplay muted playsinline></video><figcaption>You</figcaption></figure><div id="remote-videos" class="video-grid"></div></div></section></main>
<?php require_once __DIR__.'/turn_lib.php';$turnCfg=tt_turn_ice_config();?><script>window.TT_CALL_CONTEXT={user:<?=json_encode($me)?>,uid:<?=$uid?>,groups:<?=json_encode($groups)?>,events:<?=json_encode($events)?>,forums:<?=json_encode($forums)?>,tags:<?=json_encode($tags)?>,iceServers:<?=json_encode($turnCfg['servers'])?>,turnConfigured:<?=!empty($turnCfg['turn_configured'])?'true':'false'?>,turnSource:<?=json_encode($turnCfg['source'])?>,turnError:<?=json_encode($turnCfg['error'])?>};</script><script src="calls.js?v=20260916calls3"></script><script src="nsfw-blur.js?v=20260915c" defer></script></body></html>
