(()=>{
'use strict';
const C=window.TT_CALL_CONTEXT||{},q=s=>document.querySelector(s);
const scope=q('#call-scope'),scopeId=q('#call-scope-id'),scopeRef=q('#call-scope-ref'),members=q('#call-members'),priv=q('#private-label'),sl=q('#scope-label');
const camSel=q('#call-camera-device'),micSel=q('#call-mic-device'),speakerSel=q('#call-speaker-device'),previewBtn=q('#call-device-preview'),stopPreviewBtn=q('#call-device-stop'),setupVideo=q('#setup-local-video'),createSubmit=q('#call-create-submit'),joinBtn=q('#call-join');
let key=new URLSearchParams(location.search).get('join')||'',stream=null,last=0,timer=null,relaySeen=false,joined=false,deviceReady=false,selectedSinkId='';
const pcs=new Map(),names=new Map(),present=new Set(),roster=new Map();
const uid=Number(C.uid)||0;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function status(s){const n=q('#call-status');if(!n)return;n.hidden=false;n.textContent=s;}
function deviceStatus(s){const n=q('#call-device-status');if(n)n.textContent=s;}
function localState(text){const n=q('#local-media-state');if(n)n.textContent=text;const p=q('#setup-media-state');if(p)p.textContent=text;}
async function fetchJson(url,opts={}){
  const headers=new Headers(opts.headers||{});if(C.apiToken)headers.set('X-Tabletime-Call-Token',C.apiToken);opts.headers=headers;opts.credentials='same-origin';opts.cache='no-store';
  const r=await fetch(url,opts);const ct=(r.headers.get('content-type')||'').toLowerCase();
  if(!ct.includes('application/json')){if(r.redirected||/login\.php/i.test(r.url||''))throw Error('Your Tabletime login needs to be restored. Reopen Calls or sign in again.');throw Error('Call service returned an unexpected response.');}
  const d=await r.json();if(r.status===401||d.error==='login_required')throw Error(d.message||'Login required.');return d;
}
function api(a,data={},method='POST'){
  if(method==='GET')return fetchJson('api/call_signal.php?'+new URLSearchParams({action:a,auth_token:C.apiToken||'',...data}));
  const fd=new FormData();fd.set('action',a);if(C.apiToken)fd.set('auth_token',C.apiToken);for(const[k,v]of Object.entries(data))fd.set(k,v);return fetchJson('api/call_signal.php',{method:'POST',body:fd});
}
function listFor(t){return t==='group'?C.groups:t==='event'?C.events:t==='forum'?C.forums:t==='tag'?C.tags:[];}
function fill(){const t=scope.value,x=listFor(t);scopeId.innerHTML=x.map(v=>`<option value="${Number(v.id)||0}" data-ref="${esc(v.title)}">${esc(v.title)}</option>`).join('');const needs=['group','event','forum','tag'].includes(t),privateMode=t==='private';scopeId.hidden=sl.hidden=!needs;members.hidden=priv.hidden=!privateMode;scopeRef.value=scopeId.options[scopeId.selectedIndex]?.dataset.ref||'';}
scope?.addEventListener('change',fill);scopeId?.addEventListener('change',()=>scopeRef.value=scopeId.options[scopeId.selectedIndex]?.dataset.ref||'');if(scope)fill();

function sinkSupported(){return !!(window.HTMLMediaElement&&HTMLMediaElement.prototype&&typeof HTMLMediaElement.prototype.setSinkId==='function');}
async function applySink(v){if(!v||!selectedSinkId||!sinkSupported())return;try{await v.setSinkId(selectedSinkId);}catch(_){}}
function safePlay(v){if(!v)return;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','');v.playsInline=true;v.autoplay=true;if(v.id==='local-video'||v.id==='setup-local-video'){v.muted=true;v.defaultMuted=true;}applySink(v);const p=v.play?.();if(p&&typeof p.catch==='function')p.catch(()=>{let b=v.parentElement?.querySelector('.tt-video-play');if(!b){b=document.createElement('button');b.type='button';b.className='tt-video-play';b.textContent='Tap to play video';b.onclick=()=>{v.play().then(()=>b.remove()).catch(()=>{});};v.parentElement?.appendChild(b);}});}
function attachLocal(s){for(const v of [setupVideo,q('#local-video')])if(v){v.muted=true;v.defaultMuted=true;v.srcObject=s;v.onloadedmetadata=()=>safePlay(v);safePlay(v);}}
function selectedValue(sel){return sel&&sel.value?sel.value:'';}
function fillDeviceSelect(sel,items,label,current=''){if(!sel)return;const old=current||sel.value||'';sel.innerHTML='';const def=document.createElement('option');def.value='';def.textContent='System / browser default';sel.appendChild(def);items.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`${label} ${i+1}`;sel.appendChild(o);});if(old&&[...sel.options].some(o=>o.value===old))sel.value=old;}
async function enumerateDevices(preferred={}){
  if(!navigator.mediaDevices?.enumerateDevices)return;
  try{const all=await navigator.mediaDevices.enumerateDevices();fillDeviceSelect(camSel,all.filter(d=>d.kind==='videoinput'),'Camera',preferred.camera||selectedValue(camSel));fillDeviceSelect(micSel,all.filter(d=>d.kind==='audioinput'),'Microphone',preferred.mic||selectedValue(micSel));const outs=all.filter(d=>d.kind==='audiooutput');fillDeviceSelect(speakerSel,outs,'Speaker',preferred.speaker||selectedValue(speakerSel));if(!sinkSupported()){speakerSel.disabled=true;speakerSel.innerHTML='<option value="">System output (browser controlled)</option>';}else speakerSel.disabled=false;}catch(e){deviceStatus('Device list unavailable until browser permission is granted.');}
}
function currentDeviceIds(s){const v=s?.getVideoTracks?.()[0]?.getSettings?.().deviceId||'',a=s?.getAudioTracks?.()[0]?.getSettings?.().deviceId||'';return{camera:v,mic:a,speaker:selectedSinkId};}
function mediaConstraints(){const c=selectedValue(camSel),m=selectedValue(micSel);return{video:c?{deviceId:{exact:c}}:{facingMode:'user'},audio:m?{deviceId:{exact:m}}:true};}
async function replaceOutgoing(next){for(const p of pcs.values()){for(const kind of ['video','audio']){const tr=next.getTracks().find(t=>t.kind===kind),sender=p.getSenders().find(s=>s.track?.kind===kind);if(sender&&tr)try{await sender.replaceTrack(tr);}catch(_){}}}}
function updateReadyControls(){if(createSubmit){createSubmit.disabled=!deviceReady;createSubmit.textContent=deviceReady?'Create call':'Preview devices first';}if(joinBtn){joinBtn.disabled=!deviceReady||!key;joinBtn.textContent=deviceReady?'Join call':'Preview devices first';}if(stopPreviewBtn)stopPreviewBtn.disabled=!stream;}
async function startPreview(force=false){
  if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera/microphone is unavailable here. Use HTTPS and allow browser permissions.');
  if(stream&&!force){attachLocal(stream);deviceReady=true;updateReadyControls();return stream;}
  localState('Requesting selected camera/microphone…');deviceStatus('Waiting for browser device permission…');
  const previous=stream;let next;
  try{next=await navigator.mediaDevices.getUserMedia(mediaConstraints());}catch(e){localState('Device permission failed');deviceStatus(e.message||'Camera/microphone permission was denied.');throw e;}
  stream=next;attachLocal(stream);await replaceOutgoing(stream);if(previous&&previous!==stream)previous.getTracks().forEach(t=>t.stop());
  const ids=currentDeviceIds(stream);await enumerateDevices(ids);deviceReady=true;updateReadyControls();
  const vt=stream.getVideoTracks()[0],at=stream.getAudioTracks()[0];localState(vt&&vt.readyState==='live'?'You · camera live':'You · camera permission granted');deviceStatus(`Ready: ${vt?.label||'camera'} · ${at?.label||'microphone'}`);return stream;
}
function stopPreview(){if(joined)return;stream?.getTracks().forEach(t=>t.stop());stream=null;deviceReady=false;for(const v of [setupVideo,q('#local-video')])if(v)v.srcObject=null;localState('Devices not enabled yet');deviceStatus('Preview stopped. Enable devices before creating or joining a call.');updateReadyControls();}
previewBtn&&(previewBtn.onclick=()=>startPreview(!!stream).catch(e=>status(e.message||String(e))));
stopPreviewBtn&&(stopPreviewBtn.onclick=stopPreview);
camSel?.addEventListener('change',()=>{if(stream)startPreview(true).catch(e=>status(e.message||String(e)));});
micSel?.addEventListener('change',()=>{if(stream)startPreview(true).catch(e=>status(e.message||String(e)));});
speakerSel?.addEventListener('change',async()=>{selectedSinkId=speakerSel.value||'';for(const v of document.querySelectorAll('#participant-grid video'))await applySink(v);deviceStatus(selectedSinkId?'Selected speaker/output updated.':'Using system/default speaker output.');});
navigator.mediaDevices?.addEventListener?.('devicechange',()=>enumerateDevices(currentDeviceIds(stream)));
enumerateDevices();updateReadyControls();

function ensureTile(id,username,state='Present · waiting for video'){
  id=Number(id);if(!id||id===uid)return q('#participant-self');names.set(id,username||names.get(id)||('User '+id));
  let f=document.getElementById('peer-tile-'+id);if(!f){f=document.createElement('figure');f.id='peer-tile-'+id;f.className='participant-tile';const v=document.createElement('video');v.id='peer-'+id;v.autoplay=true;v.playsInline=true;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','');const c=document.createElement('figcaption');const strong=document.createElement('strong');strong.className='participant-name';strong.textContent=names.get(id);const st=document.createElement('span');st.className='participant-state';st.textContent=state;c.append(strong,st);f.append(v,c);q('#participant-grid')?.appendChild(f);}else{const n=f.querySelector('.participant-name');if(n)n.textContent=names.get(id);const st=f.querySelector('.participant-state');if(st&&state)st.textContent=state;}return f;
}
function tileState(id,text){const f=id===uid?q('#participant-self'):document.getElementById('peer-tile-'+Number(id));const st=f?.querySelector('.participant-state');if(st)st.textContent=text;}
function setRoster(invited=[]){for(const x of invited||[]){const id=Number(x.id);if(!id)continue;const username=x.username||('User '+id);roster.set(id,username);names.set(id,username);if(id!==uid)ensureTile(id,username,'Invited · not joined');}}
function setPresence(peers=[]){present.clear();present.add(uid);for(const x of peers){const id=Number(x.id);if(!id)continue;present.add(id);const username=x.username||roster.get(id)||('User '+id);roster.set(id,username);names.set(id,username);if(id!==uid)ensureTile(id,username,'Present · connecting');}for(const [id,username] of roster){if(id!==uid&&!present.has(id))ensureTile(id,username,'Invited · not joined');}for(const [id,p] of pcs){if(!present.has(Number(id))){tileState(id,roster.has(Number(id))?'Invited · not joined':'Disconnected');if(p.connectionState!=='closed')try{p.close();}catch(_){ }pcs.delete(Number(id));}}}
async function dashboard(){try{const d=await fetchJson('api/call_presence.php?'+new URLSearchParams({auth_token:C.apiToken||''}));const box=q('#call-dashboard');if(!box)return;box.innerHTML=(d.calls||[]).map(c=>`<div class="call-presence-row"><strong>${esc(c.title)}</strong> <span class="meta">${esc(c.scope_type)} · ${c.joined?'active':'incoming'}</span> <button type="button" data-pop="${esc(c.call_key)}">${c.joined?'Open call window':'Answer / join'}</button></div>`).join('')||'<p class="meta">No active or incoming calls.</p>';box.querySelectorAll('[data-pop]').forEach(b=>b.onclick=()=>openCall(b.dataset.pop));}catch(e){if(/login/i.test(e.message||''))status(e.message);}}
function openCall(k){const u='calls.php?join='+encodeURIComponent(k)+'&callwindow=1',w=window.open(u,'ttcall-'+k,'popup=yes,width=900,height=720');if(!w)location.href=u;}
function prepareRoom(title='Call'){const room=q('#call-room');if(room)room.hidden=false;const h=q('#call-heading');if(h)h.textContent=title;if(stream)attachLocal(stream);localState(stream?'You · camera ready':'Preview devices first');updateReadyControls();}
async function loadRoomInfo(){if(!key)return;prepareRoom('Loading call…');try{const d=await api('info',{call_key:key},'GET');prepareRoom(d.call?.title||'Call');setRoster(d.invited||[]);setPresence(d.peers||[]);status('Room loaded. Choose/preview devices, then join. Participant usernames are shown before video connects.');}catch(e){status(e.message||String(e));}}

q('#call-create')?.addEventListener('submit',async e=>{e.preventDefault();try{if(!deviceReady)await startPreview(false);scopeRef.value=scopeId.options[scopeId.selectedIndex]?.dataset.ref||scopeRef.value||'';const d=await api('create',{scope_type:scope.value,scope_id:scopeId.value||0,scope_ref:scopeRef.value,members:members.value,title:q('#call-title').value});if(d.error)throw Error(d.error);key=d.call_key;setRoster(Object.entries(d.members||{}).map(([username,id])=>({id:Number(id),username})));history.replaceState(null,'','calls.php?join='+key);prepareRoom(d.title||q('#call-title').value);status(d.reused?'Existing room found for this target. Joining with your selected devices…':'Call created. Joining with your selected devices…');await join();dashboard();}catch(e){status(e.message||String(e));}});
async function media(){if(stream)return stream;return startPreview(false);}
async function pc(peer,username,initiator=false){peer=Number(peer);if(peer===uid)return null;if(pcs.has(peer))return pcs.get(peer);names.set(peer,username||('User '+peer));ensureTile(peer,names.get(peer),'Present · negotiating video');await media();const p=new RTCPeerConnection({iceServers:C.iceServers||[{urls:'stun:stun.l.google.com:19302'}]});pcs.set(peer,p);for(const tr of stream.getTracks())p.addTrack(tr,stream);p.onicecandidate=e=>{if(e.candidate&&(e.candidate.type==='relay'||/\styp\s+relay\b/i.test(e.candidate.candidate||''))){relaySeen=true;status('TURN relay active as fallback.');}if(e.candidate)api('signal',{call_key:key,to:peer,signal_type:'ice',payload:JSON.stringify(e.candidate)}).catch(()=>{});};p.ontrack=e=>remote(peer,e.streams?.[0]||new MediaStream([e.track]));p.onconnectionstatechange=()=>{const st=p.connectionState;if(st==='connected'){tileState(peer,'Video connected');if(!relaySeen&&C.turnConfigured)status('Connected directly. TURN remains available only as fallback.');}else if(st==='connecting')tileState(peer,'Present · connecting');else if(['failed','closed','disconnected'].includes(st))tileState(peer,st==='disconnected'?'Connection interrupted':'Disconnected');};if(initiator){const o=await p.createOffer();await p.setLocalDescription(o);await api('signal',{call_key:key,to:peer,signal_type:'offer',payload:JSON.stringify(o)});}return p;}
function remote(id,s){const f=ensureTile(id,names.get(Number(id))||('User '+id),'Video connected');const v=f?.querySelector('video');if(v){v.srcObject=s;safePlay(v);}tileState(id,'Video connected');}
async function signals(){const d=await api('poll',{call_key:key,after:last},'GET');for(const s of d.signals||[]){last=Math.max(last,Number(s.id)||0);const from=Number(s.from_account_id);names.set(from,s.username);ensureTile(from,s.username,'Present · signaling');let p=pcs.get(from);if(s.signal_type==='offer'){p=await pc(from,s.username,false);await p.setRemoteDescription(JSON.parse(s.payload));const a=await p.createAnswer();await p.setLocalDescription(a);await api('signal',{call_key:key,to:from,signal_type:'answer',payload:JSON.stringify(a)});}else if(s.signal_type==='answer'&&p){await p.setRemoteDescription(JSON.parse(s.payload));}else if(s.signal_type==='ice'&&p){try{await p.addIceCandidate(JSON.parse(s.payload));}catch(_){}}}}
async function beat(){if(!joined)return;try{const d=await api('heartbeat',{call_key:key});if(d.error)throw Error(d.error);setRoster(d.invited||[]);setPresence(d.peers||[]);for(const x of d.peers||[]){const id=Number(x.id);if(id!==uid&&!pcs.has(id)&&uid<id)pc(id,x.username,true).catch(e=>tileState(id,e.message||'Connection error'));}await signals();}catch(e){status(e.message||String(e));}}
async function join(){if(joined||!key)return;try{if(!deviceReady)await startPreview(false);if(joinBtn)joinBtn.disabled=true;prepareRoom('Joining call…');const d=await api('join',{call_key:key});if(d.error)throw Error(d.error);joined=true;prepareRoom(d.call?.title||'Call');setRoster(d.invited||[]);setPresence(d.peers||[]);q('#call-camera').disabled=q('#call-mic').disabled=q('#call-share').disabled=q('#call-leave').disabled=false;stopPreviewBtn&&(stopPreviewBtn.disabled=true);for(const x of d.peers||[]){const id=Number(x.id);if(id!==uid){ensureTile(id,x.username,'Present · connecting');if(uid<id)pc(id,x.username,true).catch(e=>tileState(id,e.message||'Connection error'));}}timer=setInterval(beat,2500);status(`Connected to call (${Number(d.participant_count)||1}/${Number(d.max_participants)||86}). Participant cells stay visible even while video negotiates.`);dashboard();}catch(e){updateReadyControls();status(e.message||String(e));}}
joinBtn&&(joinBtn.onclick=join);
q('#call-camera')&&(q('#call-camera').onclick=()=>stream?.getVideoTracks().forEach(t=>{t.enabled=!t.enabled;localState(t.enabled?'You · camera on':'You · camera off');}));
q('#call-mic')&&(q('#call-mic').onclick=()=>stream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled));
q('#call-share')&&(q('#call-share').onclick=async()=>{try{const ds=await navigator.mediaDevices.getDisplayMedia({video:true});const tr=ds.getVideoTracks()[0];for(const p of pcs.values()){const snd=p.getSenders().find(s=>s.track?.kind==='video');if(snd)await snd.replaceTrack(tr);}tr.onended=async()=>{const cam=stream?.getVideoTracks()[0];for(const p of pcs.values()){const snd=p.getSenders().find(s=>s.track?.kind==='video');if(snd&&cam)await snd.replaceTrack(cam);}};}catch(e){status(e.message||'Screen sharing was cancelled.');}});
q('#call-leave')&&(q('#call-leave').onclick=async()=>{clearInterval(timer);try{await api('leave',{call_key:key});}catch(_){ }for(const p of pcs.values())try{p.close();}catch(_){ }stream?.getTracks().forEach(t=>t.stop());joined=false;location.href='calls.php';});
if(key)loadRoomInfo();dashboard();setInterval(dashboard,5000);
})();
