<?php
require_once dirname(__DIR__).'/session_bootstrap.php';$ttCallToken=(string)($_SERVER['HTTP_X_TABLETIME_CALL_TOKEN']??($_REQUEST['auth_token']??''));if((empty($_SESSION['loggedin'])||empty($_SESSION['id']))&&$ttCallToken!=='')tt_restore_call_api_token($ttCallToken);if(empty($_SESSION['loggedin'])||empty($_SESSION['id'])){header('Content-Type: application/json; charset=utf-8');http_response_code(401);echo json_encode(['error'=>'login_required','message'=>'Your Tabletime login needs to be restored. Reopen Calls or sign in again.']);exit;}require_once dirname(__DIR__).'/core.php';header('Content-Type: application/json; charset=utf-8');$db=tt_db_open(true);$uid=(int)$_SESSION['id'];$me=(string)$_SESSION['name'];$action=(string)($_REQUEST['action']??'');
function out($v,int $code=200){http_response_code($code);echo json_encode($v,JSON_UNESCAPED_SLASHES);exit;}
function getcall(mysqli $db,string $key){$q=$db->prepare('SELECT `id`,`scope_type`,`scope_id`,`created_by`,`title`,`members`,`status` FROM `calls` WHERE `call_key`=? LIMIT 1');$q->bind_param('s',$key);$q->execute();$r=$q->get_result()?->fetch_assoc();$q->close();return $r;}
function allowed(array $c,string $me):bool{return $c['scope_type']==='default'||in_array($me,tt_member_list((string)$c['members']),true);}
function active_count(mysqli $db,int $uid):int{$q=$db->prepare("SELECT COUNT(DISTINCT c.id) FROM calls c LEFT JOIN call_participants p ON p.call_id=c.id AND p.account_id=? AND p.left_at IS NULL AND p.last_seen_at>UTC_TIMESTAMP()-INTERVAL 60 SECOND WHERE c.status='open' AND c.updated_at>UTC_TIMESTAMP()-INTERVAL 30 MINUTE AND (p.account_id IS NOT NULL OR c.created_by=?)");$q->bind_param('ii',$uid,$uid);$q->execute();$q->bind_result($n);$q->fetch();$q->close();return(int)$n;}
const TT_CALL_MAX_PARTICIPANTS=86;
function call_target_key(string $scope,int $sid,string $ref,array $ids,int $creator):string{
 $scope=strtolower(trim($scope));$ref=strtolower(trim($ref));$idvals=array_values(array_map('intval',$ids));sort($idvals,SORT_NUMERIC);
 if($scope==='private')$identity='private:'.implode(',',$idvals);
 elseif(in_array($scope,['group','event','forum'],true)&&$sid>0)$identity=$scope.':id:'.$sid;
 elseif(in_array($scope,['forum','tag'],true)&&$ref!=='')$identity=$scope.':ref:'.$ref;
 elseif($scope==='default')$identity='default:creator:'.$creator;
 else $identity=$scope.':members:'.implode(',',$idvals);
 return hash('sha256',$identity);
}
function call_active_participants(mysqli $db,int $cid):int{$q=$db->prepare('SELECT COUNT(*) FROM call_participants WHERE call_id=? AND left_at IS NULL AND last_seen_at>UTC_TIMESTAMP()-INTERVAL 60 SECOND');$q->bind_param('i',$cid);$q->execute();$q->bind_result($n);$q->fetch();$q->close();return(int)$n;}
function call_invited_roster(mysqli $db,array $c):array{$names=tt_member_list((string)($c['members']??''));$ids=tt_user_ids($db,$names);$out=[];foreach($ids as $username=>$id)$out[]=['id'=>(int)$id,'username'=>(string)$username];return $out;}
try{
 if($action==='create'){
  if(active_count($db,$uid)>=3)out(['error'=>'You already have three active calls. Leave one before creating another.'],429);
  $delay=tt_delay_status($db,'call',$uid);if(!$delay['allowed'])out(['error'=>$delay['infinite']?'Call creation is locked at ∞ by Karma/Moksha/voteban balance.':'Call creation is timing-locked for another '.tt_delay_human((int)$delay['remaining']).'.'],429);
  $scope=strtolower((string)($_POST['scope_type']??'default'));if(!in_array($scope,['default','private','group','event','forum','tag'],true))out(['error'=>'invalid scope'],400);
  $sid=(int)($_POST['scope_id']??0);$ref=substr(trim((string)($_POST['scope_ref']??'')),0,191);$title=substr(trim((string)($_POST['title']??'Tabletime call')),0,255);
  $members=tt_scope_members($db,$scope,$sid?:null,(string)($_POST['members']??''),$ref);if(!in_array($me,$members,true))$members[]=$me;$ids=tt_user_ids($db,$members);
  if(count($ids)<($scope==='private'?2:1))out(['error'=>'No valid call members were found.'],400);
  $targetKey=call_target_key($scope,$sid,$ref,$ids,$uid);$memberNames=array_keys($ids);sort($memberNames,SORT_NATURAL|SORT_FLAG_CASE);$ms=tt_member_string($memberNames);$sidv=$sid?:null;$existing=null;$hasTarget=tt_schema_column_exists($db,'calls','target_key');
  if($hasTarget){$q=$db->prepare("SELECT `id`,`call_key`,`title` FROM `calls` WHERE `target_key`=? AND `status`='open' AND `updated_at`>UTC_TIMESTAMP()-INTERVAL 30 MINUTE ORDER BY `updated_at` DESC LIMIT 1");$q->bind_param('s',$targetKey);}
  else{$q=$db->prepare("SELECT `id`,`call_key`,`title` FROM `calls` WHERE `scope_type`=? AND (`scope_id`<=>?) AND `members`=? AND `status`='open' AND `updated_at`>UTC_TIMESTAMP()-INTERVAL 30 MINUTE ORDER BY `updated_at` DESC LIMIT 1");$q->bind_param('sis',$scope,$sidv,$ms);}
  $q->execute();$existing=$q->get_result()?->fetch_assoc();$q->close();
  if($existing){$cid=(int)$existing['id'];if(call_active_participants($db,$cid)>=TT_CALL_MAX_PARTICIPANTS)out(['error'=>'That call already has 86 active participants.'],429);out(['ok'=>true,'call_key'=>$existing['call_key'],'members'=>$ids,'title'=>$existing['title']?:$title,'reused'=>true,'max_participants'=>TT_CALL_MAX_PARTICIPANTS]);}
  $key=bin2hex(random_bytes(16));if($hasTarget){$q=$db->prepare('INSERT INTO `calls` (`call_key`,`scope_type`,`scope_id`,`target_key`,`created_by`,`title`,`members`) VALUES (?,?,?,?,?,?,?)');$q->bind_param('ssisiss',$key,$scope,$sidv,$targetKey,$uid,$title,$ms);}else{$q=$db->prepare('INSERT INTO `calls` (`call_key`,`scope_type`,`scope_id`,`created_by`,`title`,`members`) VALUES (?,?,?,?,?,?)');$q->bind_param('ssiiss',$key,$scope,$sidv,$uid,$title,$ms);}$q->execute();$q->close();
  foreach($ids as $name=>$id)if($id!==$uid)tt_notify($db,$id,'call','Incoming '.$scope.' call',$me.' invited you to '.$title,'calls.php?join='.$key);tt_delay_mark_success($db,'call',$uid);out(['ok'=>true,'call_key'=>$key,'members'=>$ids,'title'=>$title,'reused'=>false,'max_participants'=>TT_CALL_MAX_PARTICIPANTS]);
 }
 $key=(string)($_REQUEST['call_key']??'');if(!preg_match('/^[a-f0-9]{32}$/',$key))out(['error'=>'invalid call'],400);$c=getcall($db,$key);if(!$c||$c['status']!=='open'||!allowed($c,$me))out(['error'=>'call unavailable'],403);$cid=(int)$c['id'];
 if($action==='info'){
  $r=$db->query('SELECT `account_id`,`username` FROM `call_participants` WHERE `call_id`='.$cid.' AND `left_at` IS NULL AND `last_seen_at`>UTC_TIMESTAMP()-INTERVAL 45 SECOND');$peers=[];while($r&&$x=$r->fetch_assoc())$peers[]=['id'=>(int)$x['account_id'],'username'=>$x['username']];if($r)$r->free();
  out(['ok'=>true,'call'=>['title'=>$c['title'],'scope_type'=>$c['scope_type']],'peers'=>$peers,'invited'=>call_invited_roster($db,$c),'participant_count'=>count($peers),'max_participants'=>TT_CALL_MAX_PARTICIPANTS]);
 }
 if($action==='join'||$action==='heartbeat'){
  if($action==='join'){$q=$db->prepare('SELECT COUNT(*) FROM call_participants WHERE call_id=? AND account_id=? AND left_at IS NULL AND last_seen_at>UTC_TIMESTAMP()-INTERVAL 60 SECOND');$q->bind_param('ii',$cid,$uid);$q->execute();$q->bind_result($already);$q->fetch();$q->close();if(!$already&&active_count($db,$uid)>=3)out(['error'=>'Three-call limit reached. Leave one active call before joining another.'],429);if($c['scope_type']==='default'&&!in_array($me,tt_member_list((string)$c['members']),true)){$m=tt_member_list((string)$c['members']);$m[]=$me;$ms=tt_member_string($m);$q=$db->prepare('UPDATE calls SET members=? WHERE id=?');$q->bind_param('si',$ms,$cid);$q->execute();$q->close();}}
  if($action==='join'&&!$already&&call_active_participants($db,$cid)>=TT_CALL_MAX_PARTICIPANTS)out(['error'=>'This call has reached its 86-participant limit.'],429);
  $q=$db->prepare('INSERT INTO `call_participants` (`call_id`,`account_id`,`username`,`joined_at`,`last_seen_at`,`left_at`) VALUES (?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP(),NULL) ON DUPLICATE KEY UPDATE `username`=VALUES(`username`),`last_seen_at`=UTC_TIMESTAMP(),`left_at`=NULL');$q->bind_param('iis',$cid,$uid,$me);$q->execute();$q->close();$db->query('UPDATE `calls` SET `updated_at`=UTC_TIMESTAMP() WHERE `id`='.$cid);
  $r=$db->query('SELECT `account_id`,`username` FROM `call_participants` WHERE `call_id`='.$cid.' AND `left_at` IS NULL AND `last_seen_at`>UTC_TIMESTAMP()-INTERVAL 45 SECOND');$peers=[];while($r&&$x=$r->fetch_assoc())$peers[]=['id'=>(int)$x['account_id'],'username'=>$x['username']];if($r)$r->free();out(['ok'=>true,'call'=>['title'=>$c['title'],'scope_type'=>$c['scope_type']],'peers'=>$peers,'invited'=>call_invited_roster($db,$c),'participant_count'=>count($peers),'max_participants'=>TT_CALL_MAX_PARTICIPANTS,'active_count'=>active_count($db,$uid)]);
 }
 if($action==='signal'){$to=(int)($_POST['to']??0);$type=(string)($_POST['signal_type']??'');$payload=(string)($_POST['payload']??'');if(!in_array($type,['offer','answer','ice','renegotiate'],true)||strlen($payload)>131072)out(['error'=>'invalid signal'],400);$toV=$to?:null;$q=$db->prepare('INSERT INTO `call_signals` (`call_id`,`from_account_id`,`to_account_id`,`signal_type`,`payload`) VALUES (?,?,?,?,?)');$q->bind_param('iiiss',$cid,$uid,$toV,$type,$payload);$q->execute();$q->close();out(['ok'=>true]);}
 if($action==='poll'){$after=max(0,(int)($_GET['after']??0));$q=$db->prepare('SELECT s.`id`,s.`from_account_id`,a.`username`,s.`signal_type`,s.`payload` FROM `call_signals` s JOIN `accounts` a ON a.`id`=s.`from_account_id` WHERE s.`call_id`=? AND s.`id`>? AND s.`from_account_id`<>? AND (s.`to_account_id` IS NULL OR s.`to_account_id`=?) ORDER BY s.`id` ASC LIMIT 200');$q->bind_param('iiii',$cid,$after,$uid,$uid);$q->execute();$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);$q->close();out(['ok'=>true,'signals'=>$rows]);}
 if($action==='leave'){$q=$db->prepare('UPDATE `call_participants` SET `left_at`=UTC_TIMESTAMP(),`last_seen_at`=UTC_TIMESTAMP() WHERE `call_id`=? AND `account_id`=?');$q->bind_param('ii',$cid,$uid);$q->execute();$q->close();$r=$db->query('SELECT COUNT(*) n FROM call_participants WHERE call_id='.$cid.' AND left_at IS NULL AND last_seen_at>UTC_TIMESTAMP()-INTERVAL 60 SECOND');$n=(int)($r?($r->fetch_assoc()['n']??0):0);if($r)$r->free();if($n===0)$db->query("UPDATE calls SET status='closed',updated_at=UTC_TIMESTAMP() WHERE id=".$cid);out(['ok'=>true]);}
 out(['error'=>'unknown action'],400);
}catch(Throwable $e){out(['error'=>'call service error'],500);}
