<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/tag_engine.php';require_once __DIR__.'/maintenance.php';require_once __DIR__.'/federation_lib.php';tt_require_login();
if($_SERVER['REQUEST_METHOD']!=='POST'||!isset($_POST['enter'])){header('Location: create.php');exit;}if((int)($_POST['test']??-1)!==((int)($_POST['no1']??0)+(int)($_POST['no2']??0)))tt_fail('Invalid captcha entered.',400,'Publish');
$con=tt_db_open(true);$authorId=(int)$_SESSION['id'];$author=(string)($_SESSION['name']??'');$type=strtolower(trim((string)($_POST['type']??'post')));$scope=strtolower(trim((string)($_POST['scope']??'public')));if(!in_array($scope,['private','public','global'],true))$scope='public';$allowed=['post','media','message','comment','event','group','forum','profile'];if(!in_array($type,$allowed,true))$type='post';$title=trim((string)($_POST['title']??''));$content=trim((string)($_POST['content']??''));$tags=tt_compact_tags((string)($_POST['tags']??''),4096);$recipients=substr(trim((string)($_POST['recipients']??'')),0,4096);$dt=gmdate('Y-m-d H:i:s');if($title===''||$content==='')tt_fail('Title and content are required.',400,'Publish');$title=substr($title,0,255);if(strlen($content)>32768)tt_fail('Post content is limited to 32 KB.',400,'Publish');
if($type==='message')$scope='private';
$attachmentName='';$attachmentMime='application/octet-stream';$attachmentData='';$attachmentSize=0;if(isset($_FILES['file'])&&($_FILES['file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){if(($_FILES['file']['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK)tt_fail('Upload failed before Tabletime received the file.',400,'Upload');$attachmentSize=(int)($_FILES['file']['size']??0);if($attachmentSize>tt_upload_limit_bytes())tt_fail('Uploads are limited to 250 KB.',400,'Upload');if($attachmentSize>0&&is_uploaded_file($_FILES['file']['tmp_name'])){$attachmentName=preg_replace('/[^A-Za-z0-9._ -]+/','_',basename((string)$_FILES['file']['name']));if($attachmentName==='')$attachmentName='upload.bin';$raw=file_get_contents($_FILES['file']['tmp_name']);if($raw===false)tt_fail('Could not read uploaded file.',400,'Upload');$attachmentData=$raw;$attachmentSize=strlen($raw);$reported=trim((string)($_FILES['file']['type']??''));if(preg_match('~^[A-Za-z0-9.+-]+/[A-Za-z0-9.+-]+$~',$reported))$attachmentMime=substr($reported,0,191);}}
$postId=0;
try{tt_preflight_write($con,strlen($title)+strlen($content)+strlen($tags)+strlen($recipients)+$attachmentSize+16384,true);$con->begin_transaction();
 if($type==='profile'){$s=tt_prepare($con,'UPDATE `accounts` SET `aboutcontent`=? WHERE `id`=?');$s->bind_param('si',$content,$authorId);if(!$s->execute())throw new RuntimeException($s->error);$s->close();$_SESSION['aboutcontent']=$content;}
 elseif($type==='comment'){$target=(int)$recipients;if($target<=0)throw new RuntimeException('For a comment, put the target post id in Recipients.');$s=tt_prepare($con,'SELECT `comments` FROM `posts` WHERE `id`=? FOR UPDATE');$s->bind_param('i',$target);$s->execute();$s->bind_result($existing);if(!$s->fetch()){$s->close();throw new RuntimeException('Target post was not found.');}$s->close();$line=$dt.' '.$author.': '.$content;$merged=trim((string)$existing."\n".$line);if(strlen($merged)>16384)$merged=substr($merged,-16384);$s=tt_prepare($con,'UPDATE `posts` SET `comments`=? WHERE `id`=?');$s->bind_param('si',$merged,$target);if(!$s->execute())throw new RuntimeException($s->error);$s->close();$postId=$target;}
 else{
   if($type==='event'){$members=tt_member_string(array_merge([$author],tt_member_list($recipients)));$groups='';$posts='';$s=tt_prepare($con,'INSERT INTO `events` (`title`,`members`,`about`,`groups`,`posts`,`tags`,`type`) VALUES (?,?,?,?,?,?,?)');$s->bind_param('sssssss',$title,$members,$content,$groups,$posts,$tags,$type);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   elseif($type==='group'){$members=tt_member_string(array_merge([$author],tt_member_list($recipients)));$events='';$posts='';$forums='';$s=tt_prepare($con,'INSERT INTO `groups` (`title`,`members`,`about`,`forums`,`events`,`posts`,`tags`) VALUES (?,?,?,?,?,?,?)');$s->bind_param('sssssss',$title,$members,$content,$forums,$events,$posts,$tags);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   elseif($type==='forum'){$groups='';$posts='';$events='';$s=tt_prepare($con,'INSERT INTO `forums` (`tag`,`posts`,`groups`,`events`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `tag`=VALUES(`tag`)');$s->bind_param('ssss',$title,$posts,$groups,$events);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   $comments='';$votes='';$file='';$s=tt_prepare($con,'INSERT INTO `posts` (`title`,`content`,`dt`,`file`,`tags`,`name`,`comments`,`scope`,`recipients`,`type`,`votes`,`pinned`,`federated`) VALUES (?,?,?,?,?,?,?,?,?,?,?,0,0)');$s->bind_param('sssssssssss',$title,$content,$dt,$file,$tags,$author,$comments,$scope,$recipients,$type,$votes);if(!$s->execute())throw new RuntimeException($s->error);$postId=(int)$con->insert_id;$s->close();
   if($attachmentSize>0){$a=tt_prepare($con,'INSERT INTO `post_attachments` (`post_id`,`filename`,`mime_type`,`size_bytes`,`data`) VALUES (?,?,?,?,?)');$null=null;$a->bind_param('issib',$postId,$attachmentName,$attachmentMime,$attachmentSize,$null);$a->send_long_data(4,$attachmentData);if(!$a->execute())throw new RuntimeException($a->error);$a->close();$file='attachment.php?post='.$postId;$u=tt_prepare($con,'UPDATE `posts` SET `file`=? WHERE `id`=?');$u->bind_param('si',$file,$postId);if(!$u->execute())throw new RuntimeException($u->error);$u->close();}
   tt_index_post_tags($con,$postId,$tags);$sid=(string)$postId;$s=tt_prepare($con,"UPDATE `accounts` SET `posts`=TRIM(BOTH ';' FROM CONCAT_WS(';',NULLIF(`posts`,''),?)) WHERE `id`=?");$s->bind_param('si',$sid,$authorId);if(!$s->execute())throw new RuntimeException($s->error);$s->close();
   if(in_array($type,['message','group','event'],true)){foreach(tt_user_ids($con,tt_member_list($recipients)) as $n=>$rid){if($rid===$authorId)continue;$kind=$type==='message'?'message':$type;$label=$type==='message'?'New message from '.$author:ucfirst($type).' invitation from '.$author;$url=$type==='message'?'messages.php':($type==='group'?'group.php':'event.php');tt_notify($con,$rid,$kind,$label,$title,$url);}}
 }
 $con->commit();
}catch(Throwable $e){@$con->rollback();$msg=$e->getMessage();$con->close();tt_fail('Could not publish: '.$msg,503,'Publish');}
$con->close();if($type==='profile'){header('Location: profile.php?updated=1');}else{header('Location: post.php'.($postId?'?posted='.$postId:'#top'));}exit;
?>