<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/tag_engine.php';require_once __DIR__.'/maintenance.php';require_once __DIR__.'/federation_lib.php';tt_require_login();
if($_SERVER['REQUEST_METHOD']!=='POST'||!isset($_POST['enter'])){header('Location: create.php');exit;}
$con=tt_db_open(true);$authorId=(int)$_SESSION['id'];$author=(string)($_SESSION['name']??'');
$type=strtolower(trim((string)($_POST['type']??'post')));$allowed=['post','media','message','comment','event','group','forum','profile'];if(!in_array($type,$allowed,true))$type='post';$action=tt_action_for_post_type($type);
if((int)($_POST['test']??-1)!==((int)($_POST['no1']??0)+(int)($_POST['no2']??0))){tt_delay_mark_failure($con,$action,$authorId);$s=tt_delay_status($con,$action,$authorId);$con->close();tt_fail('Invalid captcha entered. Delay is now '.tt_delay_human($s['duration']).' because failed attempts double the active lock.',400,'Publish');}
$scope=array_key_exists('view',$_POST)?tt_scope_from_slider($_POST['view']):strtolower(trim((string)($_POST['scope']??'public')));if(!in_array($scope,['private','public','global'],true))$scope='public';if($type==='message')$scope='private';
$title=trim((string)($_POST['title']??''));$content=trim((string)($_POST['content']??''));$tags=tt_compact_tags((string)($_POST['tags']??''),4096);$recipients=substr(trim((string)($_POST['recipients']??'')),0,4096);$dt=gmdate('Y-m-d H:i:s');
$replyToPost=max(0,(int)($_POST['reply_to_post']??0));$replyIntent=strtolower(trim((string)($_POST['reply_intent']??'')));if(!in_array($replyIntent,['reply','comment'],true))$replyIntent='';
if($title===''||$content===''){tt_delay_mark_failure($con,$action,$authorId);$con->close();tt_fail('Title and content are required.',400,'Publish');}$title=substr($title,0,255);if(strlen($content)>32768){tt_delay_mark_failure($con,$action,$authorId);$con->close();tt_fail('Post content is limited to 32 KB.',400,'Publish');}
$status=tt_delay_status($con,$action,$authorId);if(!$status['allowed']){$con->close();$left=$status['infinite']?'∞':tt_delay_human((int)$status['remaining']);tt_fail('Tabletime timing lock is active for '.$left.'. The base is '.tt_delay_human($status['base']).'; failed attempts double it and Karma/Moksha applies action delay × number of votes ÷ voteban score.',429,'Timing lock');}
$attachmentName='';$attachmentMime='application/octet-stream';$attachmentData='';$attachmentSize=0;if(isset($_FILES['file'])&&($_FILES['file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){if(($_FILES['file']['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK){tt_delay_mark_failure($con,$action,$authorId);$con->close();tt_fail('Upload failed before Tabletime received the file.',400,'Upload');}$attachmentSize=(int)($_FILES['file']['size']??0);if($attachmentSize>tt_upload_limit_bytes()){tt_delay_mark_failure($con,$action,$authorId);$con->close();tt_fail('Uploads are limited to 250 KB.',400,'Upload');}if($attachmentSize>0&&is_uploaded_file($_FILES['file']['tmp_name'])){$attachmentName=preg_replace('/[^A-Za-z0-9._ -]+/','_',basename((string)$_FILES['file']['name']));if($attachmentName==='')$attachmentName='upload.bin';$raw=file_get_contents($_FILES['file']['tmp_name']);if($raw===false){tt_delay_mark_failure($con,$action,$authorId);$con->close();tt_fail('Could not read uploaded file.',400,'Upload');}$attachmentData=$raw;$attachmentSize=strlen($raw);$reported=trim((string)($_FILES['file']['type']??''));if(preg_match('~^[A-Za-z0-9.+-]+/[A-Za-z0-9.+-]+$~',$reported))$attachmentMime=substr($reported,0,191);}}
$postId=0;
try{tt_preflight_write($con,strlen($title)+strlen($content)+strlen($tags)+strlen($recipients)+$attachmentSize+16384,true);$con->begin_transaction();
 $replyTarget=null;
 if($replyToPost>0){
   $rt=tt_prepare($con,'SELECT p.`name`,p.`type`,p.`title`,p.`comments`,a.`id` AS owner_id FROM `posts` p LEFT JOIN `accounts` a ON a.`username`=p.`name` WHERE p.`id`=? LIMIT 1 FOR UPDATE');$rt->bind_param('i',$replyToPost);$rt->execute();$replyTarget=$rt->get_result()->fetch_assoc();$rt->close();
   if(!$replyTarget && $type==='comment')throw new RuntimeException('Target post was not found.');
   if($replyTarget && $type!=='comment'){
      $relation=['reply',tt_reply_identity_tag($replyToPost),'target-user:'.(string)$replyTarget['name'],'target-type:'.tt_reply_mode_for_post_type((string)$replyTarget['type'])];
      $tags=tt_compact_tags(trim($tags.'; '.implode('; ',$relation)),4096);
   }
 }
 if($type==='profile'){$s=tt_prepare($con,'UPDATE `accounts` SET `aboutcontent`=? WHERE `id`=?');$s->bind_param('si',$content,$authorId);if(!$s->execute())throw new RuntimeException($s->error);$s->close();$_SESSION['aboutcontent']=$content;}
 elseif($type==='comment'){$target=(int)$recipients;if($target<=0)$target=$replyToPost;if($target<=0)throw new RuntimeException('For a comment, choose a target post.');if(!$replyTarget||$replyToPost!==$target){$s=tt_prepare($con,'SELECT p.`name`,p.`type`,p.`title`,p.`comments`,a.`id` AS owner_id FROM `posts` p LEFT JOIN `accounts` a ON a.`username`=p.`name` WHERE p.`id`=? LIMIT 1 FOR UPDATE');$s->bind_param('i',$target);$s->execute();$replyTarget=$s->get_result()->fetch_assoc();$s->close();if(!$replyTarget)throw new RuntimeException('Target post was not found.');}$existing=(string)($replyTarget['comments']??'');$targetAuthor=(string)($replyTarget['name']??'');$line=$dt.' '.$author.($targetAuthor!==''?' → @'.$targetAuthor:'').': '.$content;$merged=trim($existing."\n".$line);if(strlen($merged)>16384)$merged=substr($merged,-16384);$s=tt_prepare($con,'UPDATE `posts` SET `comments`=? WHERE `id`=?');$s->bind_param('si',$merged,$target);if(!$s->execute())throw new RuntimeException($s->error);$s->close();$postId=$target;$ownerId=(int)($replyTarget['owner_id']??0);if($ownerId>0&&$ownerId!==$authorId)tt_notify($con,$ownerId,'comment','New comment from '.$author,substr($content,0,255),'post.php#post-'.$target);} 
 else{
   if($type==='event'){$members=tt_member_string(array_merge([$author],tt_member_list($recipients)));$groups='';$posts='';$s=tt_prepare($con,'INSERT INTO `events` (`title`,`members`,`about`,`groups`,`posts`,`tags`,`type`) VALUES (?,?,?,?,?,?,?)');$s->bind_param('sssssss',$title,$members,$content,$groups,$posts,$tags,$type);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   elseif($type==='group'){$members=tt_member_string(array_merge([$author],tt_member_list($recipients)));$events='';$posts='';$forums='';$s=tt_prepare($con,'INSERT INTO `groups` (`title`,`members`,`about`,`forums`,`events`,`posts`,`tags`) VALUES (?,?,?,?,?,?,?)');$s->bind_param('sssssss',$title,$members,$content,$forums,$events,$posts,$tags);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   elseif($type==='forum'){$groups='';$posts='';$events='';$s=tt_prepare($con,'INSERT INTO `forums` (`tag`,`posts`,`groups`,`events`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `tag`=VALUES(`tag`)');$s->bind_param('ssss',$title,$posts,$groups,$events);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}
   $comments='';$votes='';$file='';$s=tt_prepare($con,'INSERT INTO `posts` (`title`,`content`,`dt`,`file`,`tags`,`name`,`comments`,`scope`,`recipients`,`type`,`votes`,`pinned`,`federated`) VALUES (?,?,?,?,?,?,?,?,?,?,?,0,0)');$s->bind_param('sssssssssss',$title,$content,$dt,$file,$tags,$author,$comments,$scope,$recipients,$type,$votes);if(!$s->execute())throw new RuntimeException($s->error);$postId=(int)$con->insert_id;$s->close();
   if($attachmentSize>0){$a=tt_prepare($con,'INSERT INTO `post_attachments` (`post_id`,`filename`,`mime_type`,`size_bytes`,`data`) VALUES (?,?,?,?,?)');$null=null;$a->bind_param('issib',$postId,$attachmentName,$attachmentMime,$attachmentSize,$null);$a->send_long_data(4,$attachmentData);if(!$a->execute())throw new RuntimeException($a->error);$a->close();$file='attachment.php?post='.$postId;$u=tt_prepare($con,'UPDATE `posts` SET `file`=? WHERE `id`=?');$u->bind_param('si',$file,$postId);if(!$u->execute())throw new RuntimeException($u->error);$u->close();}
   tt_index_post_tags($con,$postId,$tags);$sid=(string)$postId;$s=tt_prepare($con,"UPDATE `accounts` SET `posts`=TRIM(BOTH ';' FROM CONCAT_WS(';',NULLIF(`posts`,''),?)) WHERE `id`=?");$s->bind_param('si',$sid,$authorId);if(!$s->execute())throw new RuntimeException($s->error);$s->close();
   if(in_array($type,['message','group','event'],true)){foreach(tt_user_ids($con,tt_member_list($recipients)) as $n=>$rid){if($rid===$authorId)continue;$kind=$type==='message'?'message':$type;$label=$type==='message'?'New message from '.$author:ucfirst($type).' invitation from '.$author;$url=$type==='message'?'messages.php':($type==='group'?'group.php':'event.php');tt_notify($con,$rid,$kind,$label,$title,$url);}}
   if($replyTarget){$ownerId=(int)($replyTarget['owner_id']??0);if($ownerId>0&&$ownerId!==$authorId&&!($type==='message'&&in_array((string)$replyTarget['name'],tt_member_list($recipients),true)))tt_notify($con,$ownerId,'reply','New '.$type.' reply from '.$author,$title,'post.php#post-'.$postId);}
 }
 tt_delay_mark_success($con,$action,$authorId);$con->commit();
}catch(Throwable $e){@$con->rollback();tt_delay_mark_failure($con,$action,$authorId);$msg=$e->getMessage();$con->close();tt_fail('Could not publish: '.$msg,503,'Publish');}
$con->close();if($type==='profile'){header('Location: profile.php?updated=1');}else{header('Location: post.php'.($postId?'?posted='.$postId:'#top'));}exit;
?>
