<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/ad_lib.php';require_once __DIR__.'/square_lib.php';require_once __DIR__.'/payout_lib.php';tt_require_login();
function tt_money_micros(int $m,int $places=4):string{return '$'.number_format($m/1000000,$places);}
function tt_parse_money_micros(string $raw):int{$raw=trim(str_replace(['$',','],'',$raw));if(!preg_match('/^\d+(?:\.\d{1,6})?$/',$raw))return 0;[$whole,$frac]=array_pad(explode('.',$raw,2),2,'');$frac=str_pad(substr($frac,0,6),6,'0');return ((int)$whole)*1000000+(int)$frac;}
$db=tt_db_open(true);$uid=(int)$_SESSION['id'];$ready=tt_ad_paid_schema_ready($db)&&tt_payout_schema_ready($db);$notice='';$error='';
if($ready&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&isset($_POST['request_payout'])){try{tt_ad_check_csrf();$amount=tt_parse_money_micros((string)($_POST['amount']??''));$conn=tt_square_seller_connection($db,$uid);$requestId=tt_payout_request($db,$uid,$amount,'square');$queued=false;if($conn)$queued=tt_payout_dispatch_optional($db,$requestId,$uid,$amount,(string)$conn['merchant_id']);$notice='Payout request #'.$requestId.' created'.($queued?' and queued for the configured payout dispatcher.':'.');}catch(Throwable $e){$error=$e->getMessage();}}
$total=0;$recent=[];$fundedImpressions=0;$summary=['gross'=>0,'reserved'=>0,'paid'=>0,'available'=>0,'requests'=>[]];$conn=null;
if($ready){try{$s=tt_prepare($db,"SELECT COALESCE(SUM(`amount_micros`),0),COUNT(*) FROM `ad_money_ledger` WHERE `beneficiary_account_id`=? AND `kind`='display_owner'");$s->bind_param('i',$uid);$s->execute();$s->bind_result($total,$fundedImpressions);$s->fetch();$s->close();$s=tt_prepare($db,"SELECT l.`amount_micros`,l.`created_at`,p.`title`,p.`name` AS advertiser FROM `ad_money_ledger` l LEFT JOIN `ad_boosts` b ON b.`id`=l.`boost_id` LEFT JOIN `posts` p ON p.`id`=b.`post_id` WHERE l.`beneficiary_account_id`=? AND l.`kind`='display_owner' ORDER BY l.`id` DESC LIMIT 100");$s->bind_param('i',$uid);$s->execute();$recent=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$summary=tt_payout_summary($db,$uid);$conn=tt_square_seller_connection($db,$uid);}catch(Throwable $e){$ready=false;$error='Earnings storage needs schema maintenance before this page can load. Open Database setup / maintenance once, then reload Earnings.';}}$db->close();
?><!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Earnings</title></head><body><?php tt_nav('earnings.php');?><main class="content"><h2>Earnings & payouts</h2><?php if($notice):?><p class="notice ok"><?=tt_h($notice)?></p><?php endif;?><?php if($error):?><p class="notice error"><?=tt_h($error)?></p><?php endif;?>
<?php if(!$ready):?><section class="card"><p class="notice">Square-funded earnings and payouts need one protected schema migration after this update. Run the controlled <a href="setup.php">database schema maintenance</a> once, then reload Earnings.</p></section><?php else:?>
<section class="grid earnings-grid"><article class="card"><h3>Available balance</h3><p class="earnings-total"><?=tt_money_micros((int)$summary['available'],2)?></p><p><?=number_format((int)$fundedImpressions)?> Square-funded impression<?=((int)$fundedImpressions===1?'':'s')?> credited to your pages.</p></article><article class="card"><h3>Wallet</h3><p><strong>Earned:</strong> <?=tt_money_micros((int)$summary['gross'],4)?><br><strong>Reserved/requested:</strong> <?=tt_money_micros((int)$summary['reserved'],4)?><br><strong>Paid:</strong> <?=tt_money_micros((int)$summary['paid'],4)?></p></article><article class="card"><h3>Revenue split</h3><p>Each $5 Square-funded package provides <strong>1,000 impressions</strong>. A qualifying impression on another user's page allocates <strong>$0.004 (4/5)</strong> to that display subject and <strong>$0.001 (1/5)</strong> to Tabletime.</p><p class="meta">Natural ad credits remain separate and non-cash: 1 natural credit = 1 counted impression.</p></article></section>
<section class="card"><h3>Square payout method</h3><?php if($conn):?><p><strong>Connected</strong> · merchant <code><?=tt_h((string)$conn['merchant_id'])?></code> · <?=tt_h((string)$conn['environment'])?></p><p><a href="square_setup.php">Square setup & connection instructions</a></p><?php else:?><p>Connect a Square seller account before requesting a Square payout. Your Square account should have your business profile completed and a bank account or eligible transfer destination linked in Square.</p><?php if(tt_square_oauth_ready()):?><form method="post" action="square_oauth_start.php"><button type="submit">Connect Square</button></form><?php else:?><p class="notice">Square OAuth still needs operator configuration on this host.</p><?php endif;?><p><a href="square_setup.php">Read the step-by-step Square setup guide</a></p><?php endif;?></section>
<?php if($conn && (int)$summary['available']>0):?><section class="card"><h3>Request payout</h3><form method="post"><input type="hidden" name="csrf" value="<?=tt_h(tt_ad_csrf())?>"><label>Amount (USD)</label><input type="number" name="amount" min="0.01" step="0.01" max="<?=number_format(((int)$summary['available'])/1000000,2,'.','')?>" required><button type="submit" name="request_payout" value="1">Request Square payout</button></form><p class="meta">Submitting reserves the requested amount so it cannot be requested twice. Status/history appears below.</p></section><?php endif;?>
<section class="card"><h3>Payout history</h3><?php if($summary['requests']):?><?php foreach($summary['requests'] as $r):?><p>#<?=(int)$r['id']?> · <strong><?=tt_money_micros((int)$r['amount_micros'],2)?></strong> · <?=tt_h((string)$r['method'])?> · <strong><?=tt_h((string)$r['status'])?></strong> · <?=tt_h((string)$r['created_at'])?><?php if(!empty($r['provider_reference'])):?> · ref <?=tt_h((string)$r['provider_reference'])?><?php endif;?></p><?php endforeach;?><?php else:?><p>No payout requests yet.</p><?php endif;?></section>
<section class="card"><h3>Recent Square-funded display earnings</h3><?php if($recent):?><div class="earnings-list"><?php foreach($recent as $r):?><p><strong>+<?=tt_money_micros((int)$r['amount_micros'])?></strong> · <?=tt_h((string)$r['created_at'])?> · <?=tt_h((string)($r['title']?:'Ad'))?><?=!empty($r['advertiser'])?' by '.tt_h((string)$r['advertiser']):''?></p><?php endforeach;?></div><?php else:?><p>No Square-funded display earnings yet.</p><?php endif;?></section>
<?php endif;?></main>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>
