<?php
define('TT_BROWSE_TYPE','forum');define('TT_BROWSE_TITLE','Forums');define('TT_NAV_ACTIVE','forum.php');
require_once __DIR__.'/core.php';require_once __DIR__.'/tag_engine.php';tt_require_login();
$type=TT_BROWSE_TYPE;$title=TT_BROWSE_TITLE;$user=(string)($_SESSION['name']??'');
$minutes=max(1,min(1440,(int)($_GET['minutes']??10)));$interval=$minutes*60;$focus=trim((string)($_GET['focus']??''));
$view=max(-256,min(256,(int)($_GET['view']??0)));$allScopes=!isset($_GET['view'])||!empty($_GET['all_scopes']);$scope=$allScopes?'all':tt_scope_from_slider($view);
$db=tt_db_open(true);[$vis,$params,$types]=tt_visible_where('p');$where=[$vis,'p.`type`=?'];$params[]=$type;$types.='s';
if($scope!=='all'){$where[]='TRIM(p.`scope`)=?';$params[]=$scope;$types.='s';}
$sql='SELECT p.`id`,p.`title`,p.`content`,p.`dt`,p.`tags`,p.`name`,p.`comments`,p.`scope`,p.`type`,p.`file`,p.`recipients` FROM `posts` p WHERE '.implode(' AND ',$where).' ORDER BY p.`dt` ASC,p.`id` ASC LIMIT 500';
$s=tt_prepare($db,$sql);$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$db->close();
function tt_forum_words(string $s):array{$s=function_exists('mb_strtolower')?mb_strtolower($s,'UTF-8'):strtolower($s);$parts=preg_split('/[^\pL\pN#:+_-]+/u',$s)?:[];$out=[];foreach($parts as $w){$w=trim($w);if($w!==''&&strlen($w)>=2)$out[$w]=true;}return $out;}
function tt_forum_content_relevance(string $basis,array $r):float{$a=tt_forum_words($basis);if(!$a)return 0.0;$b=tt_forum_words((string)($r['title']??'').' '.(string)($r['content']??'').' '.(string)($r['tags']??''));if(!$b)return 0.0;$hit=count(array_intersect_key($a,$b));$union=count($a+$b);$j=$union?($hit/$union):0.0;$tag=tt_tag_relevance($basis,(string)($r['tags']??''));return $j+max(-1.0,min(1.0,$tag))*0.5;}
$anchorTs=null;$basis=$focus;
if($rows){$anchorTs=strtotime((string)$rows[0]['dt'])?:time();if($basis==='')$basis=trim((string)$rows[0]['title'].'; '.(string)$rows[0]['tags']);}
$bands=[];foreach($rows as $r){$ts=strtotime((string)$r['dt'])?:($anchorTs??time());$block=$anchorTs===null?0:(int)floor(max(0,$ts-$anchorTs)/$interval);$r['_cloud_score']=tt_forum_content_relevance($basis,$r);$bands[$block][]=$r;}
$replyAffinity=tt_reply_affinity_for_view($view,$scope==='all');ksort($bands,SORT_NUMERIC);
foreach($bands as $block=>&$band){usort($band,fn($a,$b)=>(($b['_cloud_score']<=>$a['_cloud_score'])?:strcmp((string)$a['dt'],(string)$b['dt'])));$band=tt_sort_reply_threads($band,$replyAffinity);}unset($band);
?>
<!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · <?=tt_h($title)?></title></head><body><?php tt_nav(TT_NAV_ACTIVE);?>
<main class="content"><div class="actions"><a href="create.php?mode=forum">Create forum post</a><a href="post.php?type=forum">Search forums</a></div><h2><?=tt_h($title)?> · time/content cloud</h2>
<form method="get" class="card forum-cloud-controls">
<label for="forum-time-scale">Time block: <output id="forum-time-label"><?=$minutes?> min</output></label><input id="forum-time-scale" class="scope-slider" type="range" name="minutes" min="1" max="1440" step="1" value="<?=$minutes?>"><div class="slider-labels"><span>1 min</span><span>10 min default</span><span>24 h</span></div>
<label>Content relevance focus</label><input type="text" name="focus" value="<?=tt_h($focus)?>" placeholder="Optional words/tags; blank uses the first forum post as the relevance anchor">
<div class="scope-control"><label for="forum-scope-view">Scope / reply affinity: <output id="forum-scope-label"><?=tt_h($scope)?></output></label><input class="scope-slider" id="forum-scope-view" name="view" type="range" min="-256" max="256" step="1" value="<?=$view?>"><div class="slider-labels"><span>private / ordinary order</span><span>public / mixed</span><span>global / reply chains</span></div><label class="inline-check"><input type="checkbox" name="all_scopes" id="forum-all-scopes" value="1" <?=$scope==='all'?'checked':''?>> all visible scopes</label></div>
<button type="submit">Arrange cloud</button></form>
<p class="meta">The first visible forum post anchors time zero. Every occupied <?=$minutes?>-minute interval gets one horizontal row as intervals descend. Within a row, content relevance orders posts left→right, then reply-chain affinity (<?=number_format($replyAffinity*100,0)?>%) increasingly groups posts sharing canonical <code>ID#:&lt;post-id&gt;</code> relationships as scope moves toward global.</p>
<?php if($anchorTs!==null):?><p class="meta">Anchor: <?=tt_h(gmdate('Y-m-d H:i:s',$anchorTs))?> UTC · relevance basis: <?=tt_h($basis)?></p><?php endif;?>
<section class="forum-cloud">
<?php foreach($bands as $block=>$band):$start=$anchorTs+$block*$interval;$end=$start+$interval-1;?><section class="forum-time-row"><header><strong>Block #<?=$block?></strong> · <?=tt_h(gmdate('Y-m-d H:i',$start))?>–<?=tt_h(gmdate('Y-m-d H:i',$end))?> UTC · <?=count($band)?> post<?=count($band)===1?'':'s'?></header><div class="forum-row-posts">
<?php foreach($band as $r):$targetUser=tt_reply_target_user((string)$r['name'],(string)$r['recipients'],$user);$replyMode=tt_reply_mode_for_post_type((string)$r['type']);?><article class="card post-card forum-cloud-post" id="post-<?=(int)$r['id']?>" data-post-expandable="1" aria-expanded="false"><h3><?=tt_h($r['title'])?></h3><p class="meta">#<?=(int)$r['id']?> · <?=tt_h($r['name'])?> · <?=tt_h($r['dt'])?> · <?=tt_h(trim($r['scope']))?> · relevance <?=number_format((float)$r['_cloud_score'],3)?><?php if((int)($r['_reply_parent']??0)>0):?> · reply to #<?=(int)$r['_reply_parent']?><?php endif;?></p><p><?=nl2br(tt_h($r['content']))?></p><?php if($r['tags']!==''):?><div><?php foreach(tt_parse_tags((string)$r['tags']) as $tag):?><a class="tag" href="post.php?q=<?=rawurlencode($tag['raw'])?>"><?=tt_h($tag['raw'])?></a><?php endforeach;?></div><?php endif;?><?php if($r['file']!==''):?><p><a href="<?=tt_h($r['file'])?>">Attachment</a></p><?php endif;?><?php if(trim((string)$r['comments'])!==''):?><details class="comments-disclosure"><summary>Comments</summary><pre class="comments-body"><?=tt_h($r['comments'])?></pre></details><?php endif;?><div class="actions"><a href="<?=tt_h(tt_compose_url('comment',(int)$r['id'],(string)$r['name'],(string)$r['type'],(string)$r['title'],trim((string)$r['scope']),$targetUser))?>">Comment</a><a href="<?=tt_h(tt_compose_url('reply',(int)$r['id'],(string)$r['name'],(string)$r['type'],(string)$r['title'],trim((string)$r['scope']),$targetUser))?>">Reply as <?=tt_h($replyMode)?></a></div></article><?php endforeach;?>
</div></section><?php endforeach;?><?php if(!$rows):?><article class="card"><p>No forums yet.</p></article><?php endif;?></section></main>
<script>
const tm=document.getElementById('forum-time-scale'),tl=document.getElementById('forum-time-label');if(tm)tm.addEventListener('input',()=>{tl.value=tm.value+' min';tl.textContent=tl.value});
const sv=document.getElementById('forum-scope-view'),sl=document.getElementById('forum-scope-label'),all=document.getElementById('forum-all-scopes');function sn(v){v=Number(v)/256;return v<=-.5?'private':(v>=.5?'global':'public')}if(sv){sv.addEventListener('input',()=>{all.checked=false;sl.value=sn(sv.value);sl.textContent=sl.value});all.addEventListener('change',()=>{sl.value=all.checked?'all':sn(sv.value);sl.textContent=sl.value})}
</script></body></html>
