<?php
require_once __DIR__.'/session_bootstrap.php';
require_once __DIR__.'/entry_instructions.php';
header('Cache-Control: no-store, private, max-age=0');header('Pragma: no-cache');
if (!empty($_SESSION['loggedin'])) { if(!tt_age_is_passed()){header('Location: age_check.php?return=home.php',true,302);exit;} header('Location: home.php',true,302); exit; }
$num1=random_int(1,500); $num2=random_int(1,500);
?><!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Login</title></head><body><main class="content"><h1><a href="/">TABLETIME</a></h1><?php if(isset($_GET['registered'])):?><p class="notice ok">Registration complete. Log in below.</p><?php endif; ?><form method="post" action="authenticate.php"><?php $ttReturn=(string)($_GET['return']??''); if($ttReturn!==''):?><input type="hidden" name="return" value="<?=htmlspecialchars($ttReturn,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>"><?php endif;?><h2>Login</h2><label>Username</label><input name="username" required><label>Password</label><input type="password" name="password" required><label><?= $num1 ?> + <?= $num2 ?></label><input type="hidden" name="no1" value="<?= $num1 ?>"><input type="hidden" name="no2" value="<?= $num2 ?>"><input name="test" inputmode="numeric" required><label class="inline-check"><input type="checkbox" name="age18" value="1" required> I confirm that I am 18 or older.</label><input type="submit" name="submit" value="LOGIN"><p class="meta">Login has no cooldown after a successful sign-in. A failed attempt activates the original 10-minute timing rule and repeated failures escalate it; persistent sessions are restored directly on the first protected page after login.</p></form><p><a href="register.php">Create an account</a></p><?php tt_entry_instructions(); ?></main>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>
