<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/ad_lib.php';require_once __DIR__.'/tag_engine.php';require_once __DIR__.'/federation_lib.php';require_once __DIR__.'/maintenance.php';
$logged=!empty($_SESSION['loggedin']);$user=(string)($_SESSION['name']??'');$uid=(int)($_SESSION['id']??0);$q=trim((string)($_GET['q']??''));$type=strtolower(trim((string)($_GET['type']??'all')));if($type==='media')$type='post';
$view=max(-256,min(256,(int)($_GET['view']??0)));$scope='all';if(isset($_GET['scope'])&&in_array(trim((string)$_GET['scope']),['global','public','private'],true))$scope=trim((string)$_GET['scope']);elseif(isset($_GET['view'])&&!isset($_GET['all_scopes']))$scope=tt_scope_from_slider($view);
$db=tt_db_open(true);$adsReady=tt_ad_schema_ready($db);try{tt_opportunistic_maintenance($db);tt_federation_tick($db);}catch(Throwable $e){}
$where=[];$params=[];$types='';if($logged){[$v,$vp,$vt]=tt_visible_where('p');$where[]=$v;$params=array_merge($params,$vp);$types.=$vt;}else{$where[]="p.`scope` IN ('global','public','public ')";}
if($q!==''){$where[]='(p.`title` LIKE ? OR p.`content` LIKE ? OR p.`tags` LIKE ? OR p.`name` LIKE ? OR EXISTS (SELECT 1 FROM `tag_index` ti WHERE ti.`post_id`=p.`id` AND (ti.`tag` LIKE ? OR ti.`raw_token` LIKE ?)))';$like='%'.$q.'%';for($i=0;$i<6;$i++)$params[]=$like;$types.='ssssss';}
if($scope!=='all'&&in_array($scope,['global','public','private'],true)){if($scope==='private'&&!$logged)$scope='public';$where[]='TRIM(p.`scope`)=?';$params[]=$scope;$types.='s';}
if($type==='post'){$where[]="LOWER(TRIM(p.`type`)) IN ('post','media')";}elseif($type!=='all'&&in_array($type,['ad','message','event','group','forum'],true)){$where[]='p.`type`=?';$params[]=$type;$types.='s';}
if($adsReady){$sql='SELECT p.`id`,p.`title`,p.`content`,p.`dt`,p.`file`,p.`tags`,p.`name`,p.`comments`,p.`scope`,p.`recipients`,p.`type`,p.`votes`,p.`federated`,p.`origin_host`,a.`id` AS owner_account_id,pa.`mime_type` AS attachment_mime,ab.`id` AS boost_id,COALESCE(ab.`budget_mills`-ab.`spent_mills`,0) AS boost_remaining FROM `posts` p LEFT JOIN `accounts` a ON a.`username`=p.`name` LEFT JOIN `post_attachments` pa ON pa.`post_id`=p.`id` LEFT JOIN `ad_boosts` ab ON ab.`id`=(SELECT MAX(ab2.`id`) FROM `ad_boosts` ab2 WHERE ab2.`post_id`=p.`id` AND ab2.`status`=\'active\' AND ab2.`budget_mills`>ab2.`spent_mills`) WHERE '.implode(' AND ',$where).' ORDER BY (COALESCE(ab.`budget_mills`-ab.`spent_mills`,0)>0) DESC,COALESCE(ab.`budget_mills`-ab.`spent_mills`,0) DESC,p.`dt` DESC,p.`id` DESC LIMIT 250';}else{$sql='SELECT p.`id`,p.`title`,p.`content`,p.`dt`,p.`file`,p.`tags`,p.`name`,p.`comments`,p.`scope`,p.`recipients`,p.`type`,p.`votes`,p.`federated`,p.`origin_host`,a.`id` AS owner_account_id,pa.`mime_type` AS attachment_mime,NULL AS boost_id,0 AS boost_remaining FROM `posts` p LEFT JOIN `accounts` a ON a.`username`=p.`name` LEFT JOIN `post_attachments` pa ON pa.`post_id`=p.`id` WHERE '.implode(' AND ',$where).' ORDER BY p.`dt` DESC,p.`id` DESC LIMIT 250';}$s=tt_prepare($db,$sql);if($types!=='')$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();if($q!==''){foreach($rows as &$r)$r['_score']=tt_tag_relevance($q,(string)$r['tags']);unset($r);usort($rows,fn($a,$b)=>(($b['_score']<=>$a['_score'])?:strcmp((string)$b['dt'],(string)$a['dt'])));} $rows=array_slice($rows,0,100);
// One Karma read for the visible result set. Karma belongs to posts and every saved rater perspective remains editable.
$ratingState=[];if($rows){$ids=implode(',',array_map(fn($r)=>(int)$r['id'],$rows));$rr=$db->query('SELECT `post_id`,`voter_account_id`,`perspective` FROM `post_ratings` WHERE `post_id` IN ('.$ids.')');while($rr&&($x=$rr->fetch_assoc())){$pid=(int)$x['post_id'];if(!isset($ratingState[$pid]))$ratingState[$pid]=['n'=>0,'sum'=>0.0,'mine'=>0];$ratingState[$pid]['n']++;$ratingState[$pid]['sum']+=tt_perspective_normalized((int)$x['perspective']);if((int)$x['voter_account_id']===$uid)$ratingState[$pid]['mine']=(int)$x['perspective'];}if($rr)$rr->free();}
foreach($rows as &$r){$pid=(int)$r['id'];$x=$ratingState[$pid]??['n'=>0,'sum'=>0.0,'mine'=>0];$r['_rating']=$x['n']>0?(int)round(max(-1,min(1,$x['sum']/$x['n']))*256):0;$r['_rating_count']=$x['n'];$r['_my_rating']=$x['mine'];}unset($r);$replyAffinity=tt_reply_affinity_for_view($view,$scope==='all');$rows=tt_sort_reply_threads($rows,$replyAffinity);$db->close();
?>
<!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Posts</title></head><body>
<?php if($logged): tt_nav('post.php'); else: ?><nav class="navtop"><div><h1><a href="/">TABLETIME</a></h1><a href="post.php">Posts</a><a href="tags.php">Tags</a><a href="extend.php">Extend</a><a href="login.php">Login</a><a href="register.php">Register</a></div></nav><?php endif;?>
<main class="content"><?php if(isset($_GET['posted'])):?><p class="notice ok">Post #<?=(int)$_GET['posted']?> published and indexed.</p><?php endif;?><?php if(isset($_GET['rated'])):?><p class="notice ok">Karma rating saved.</p><?php endif;?><?php if(isset($_GET['deleted'])):?><p class="notice ok">Post deleted; its ratings were removed too, so its delay contribution is gone.</p><?php endif;?>
<form method="get" class="searchbar scope-search"><input name="q" value="<?=tt_h($q)?>" placeholder="Search text or tags"><div class="scope-control"><label for="post-scope-view">Scope: <output id="post-scope-label"><?=tt_h($scope==='all'?'all':$scope)?></output></label><input class="scope-slider" id="post-scope-view" name="view" type="range" min="-256" max="256" step="1" value="<?=$scope==='all'?0:tt_scope_slider_value($scope)?>"><div class="slider-labels"><span>private</span><span>public</span><span>global</span></div><label class="inline-check"><input type="checkbox" name="all_scopes" id="all-scopes" value="1" <?=$scope==='all'?'checked':''?>> all visible scopes</label></div><select name="type"><option value="all">all types</option><?php foreach(['post','ad','message','event','group','forum'] as $t):?><option value="<?=$t?>" <?=$type===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select><button>Search</button></form>
<p class="meta"><?=count($rows)?> matching posts. Historical scope math is preserved: slider/256 maps ≤ −0.5 private, middle public, ≥ +0.5 global. Reply-chain affinity is <?=number_format($replyAffinity*100,0)?>%: it increases continuously toward global scope so posts connected by <code>ID#:&lt;post-id&gt;</code> stay increasingly close together.</p>
<section class="grid"><?php foreach($rows as $r):?><article class="card post-card" id="post-<?=(int)$r['id']?>"<?=tt_nsfw_attr((string)$r['title'],(string)$r['tags'])?> data-post-expandable="1" data-post-impression-id="<?=(int)$r['id']?>" aria-expanded="false" <?php if(!empty($r['boost_id'])):?>data-boost-id="<?=(int)$r['boost_id']?>" data-page-owner-id="0"<?php endif;?>><h2><?=tt_h($r['title'])?></h2><p class="meta">#<?=(int)$r['id']?> · <a class="post-author-link" href="profile.php?user=<?=rawurlencode((string)$r['name'])?>"><?=tt_h($r['name'])?></a> · <?=tt_h($r['dt'])?> · <?=tt_h(trim($r['scope']))?> · <?=tt_h(tt_canonical_post_type((string)$r['type']))?><?=!empty($r['boost_id'])?' · BOOSTED':''?><?=$r['federated']?' · federated':''?><?php if(isset($r['_score'])):?> · tag score <?=number_format((float)$r['_score'],3)?><?php endif;?><?php if((int)($r['_reply_parent']??0)>0):?> · reply to #<?=(int)$r['_reply_parent']?><?php endif;?></p><p><?=nl2br(tt_h($r['content']))?></p><?=tt_ad_attachment_html($r)?><div><?php foreach(tt_parse_tags((string)$r['tags']) as $tag):?><a class="tag" href="?q=<?=rawurlencode($tag['raw'])?>"><?=tt_h($tag['raw'])?></a><?php endforeach;?></div><?php if(trim((string)$r['comments'])!==''):?><details class="comments-disclosure"><summary>Comments</summary><pre class="comments-body"><?=tt_h($r['comments'])?></pre></details><?php endif;?>
<div class="karma-summary"><strong>Karma:</strong> <?=((int)$r['_rating']>=0?'+':'').(int)$r['_rating']?> / 256 · <?=(int)$r['_rating_count']?> rating<?=((int)$r['_rating_count']===1?'':'s')?></div>
<?php if($logged && (int)$r['owner_account_id']>0):?><form method="post" action="rate.php" class="rating-form"><input type="hidden" name="post_id" value="<?=(int)$r['id']?>"><label for="rate-<?=(int)$r['id']?>">Karma rating: <output id="rate-out-<?=(int)$r['id']?>"><?=(int)$r['_my_rating']?></output></label><input class="karma-slider" id="rate-<?=(int)$r['id']?>" type="range" name="perspective" min="-256" max="256" step="1" value="<?=(int)$r['_my_rating']?>" oninput="document.getElementById('rate-out-<?=(int)$r['id']?>').value=this.value"><div class="slider-labels"><span>−256 bad / voteban edge</span><span>0</span><span>+256 good</span></div><button type="submit">Set / update Karma</button></form><?php endif;?>
<?php if($logged):?><?php $targetUser=tt_reply_target_user((string)$r['name'],(string)$r['recipients'],$user);$replyMode=tt_reply_mode_for_post_type((string)$r['type']);?><div class="actions"><a href="<?=tt_h(tt_compose_url('comment',(int)$r['id'],(string)$r['name'],(string)$r['type'],(string)$r['title'],trim((string)$r['scope']),$targetUser))?>">Comment</a><?php if(hash_equals($user,(string)$r['name'])):?><?php if($adsReady):?><details class="boost-disclosure"><summary>Apply Ad Credits</summary><form method="post" action="boost.php" class="boost-form"><input type="hidden" name="csrf" value="<?=tt_h(tt_ad_csrf())?>"><input type="hidden" name="post_id" value="<?=(int)$r['id']?>"><label>Ad credits (1 credit = 1 impression)</label><input type="number" name="credits" min="1" step="1" value="1"><label>Target user/page</label><input name="target_user" maxlength="191" autocomplete="off" placeholder="optional existing username, @username, or profile link"><label>Target scope</label><select name="target_scope"><option>public</option><option>global</option><option>private</option></select><label>Target tags</label><input name="target_tags" maxlength="1024" placeholder="music; math; topic"><button type="submit">Apply Ad Credits</button><a href="adcredits.php">natural credits</a></form></details><?php endif;?><form method="post" action="delete.php" class="inline-form"><input type="hidden" name="post_id" value="<?=(int)$r['id']?>"><button type="submit" onclick="return confirm('Delete this post? Its ratings and their delay contribution will also be removed.')">Delete</button></form><?php endif;?></div><?php endif;?></article><?php endforeach;?><?php if(!$rows):?><article class="card"><h2>No posts matched</h2><p>Try a broader search or publish a post.</p></article><?php endif;?></section></main>

<script>const sv=document.getElementById('post-scope-view'),sl=document.getElementById('post-scope-label'),all=document.getElementById('all-scopes');function sn(v){v=Number(v)/256;return v<=-.5?'private':(v>=.5?'global':'public')}if(sv){sv.addEventListener('input',()=>{all.checked=false;sl.value=sn(sv.value);sl.textContent=sn(sv.value)});all.addEventListener('change',()=>{sl.value=all.checked?'all':sn(sv.value);sl.textContent=sl.value})}</script><script>document.querySelectorAll('[data-boost-id]').forEach(el=>{const fd=new FormData();fd.set('boost_id',el.dataset.boostId);fd.set('page_owner_id',el.dataset.pageOwnerId||'0');fetch('ad_impression.php',{method:'POST',body:fd,credentials:'same-origin',keepalive:true}).catch(()=>{});});</script>
<script>document.querySelectorAll('[data-post-impression-id]').forEach(el=>{const f=new FormData();f.set('post_id',el.dataset.postImpressionId);fetch('post_impression.php',{method:'POST',body:f,credentials:'same-origin',keepalive:true}).catch(()=>{});});</script>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>
