<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/tag_engine.php';require_once __DIR__.'/federation_lib.php';require_once __DIR__.'/maintenance.php';
$logged=!empty($_SESSION['loggedin']);$user=(string)($_SESSION['name']??'');$uid=(int)($_SESSION['id']??0);$q=trim((string)($_GET['q']??''));$type=trim((string)($_GET['type']??'all'));
$view=max(-256,min(256,(int)($_GET['view']??0)));$scope='all';if(isset($_GET['scope'])&&in_array(trim((string)$_GET['scope']),['global','public','private'],true))$scope=trim((string)$_GET['scope']);elseif(isset($_GET['view'])&&!isset($_GET['all_scopes']))$scope=tt_scope_from_slider($view);
$db=tt_db_open(true);try{tt_opportunistic_maintenance($db);tt_federation_tick($db);}catch(Throwable $e){}
$where=[];$params=[];$types='';if($logged){[$v,$vp,$vt]=tt_visible_where('p');$where[]=$v;$params=array_merge($params,$vp);$types.=$vt;}else{$where[]="p.`scope` IN ('global','public','public ')";}
if($q!==''){$where[]='(p.`title` LIKE ? OR p.`content` LIKE ? OR p.`tags` LIKE ? OR p.`name` LIKE ? OR EXISTS (SELECT 1 FROM `tag_index` ti WHERE ti.`post_id`=p.`id` AND (ti.`tag` LIKE ? OR ti.`raw_token` LIKE ?)))';$like='%'.$q.'%';for($i=0;$i<6;$i++)$params[]=$like;$types.='ssssss';}
if($scope!=='all'&&in_array($scope,['global','public','private'],true)){if($scope==='private'&&!$logged)$scope='public';$where[]='TRIM(p.`scope`)=?';$params[]=$scope;$types.='s';}
if($type!=='all'&&in_array($type,['post','media','message','event','group','forum'],true)){$where[]='p.`type`=?';$params[]=$type;$types.='s';}
$sql='SELECT p.`id`,p.`title`,p.`content`,p.`dt`,p.`file`,p.`tags`,p.`name`,p.`comments`,p.`scope`,p.`recipients`,p.`type`,p.`votes`,p.`federated`,p.`origin_host`,a.`id` AS owner_account_id FROM `posts` p LEFT JOIN `accounts` a ON a.`username`=p.`name` WHERE '.implode(' AND ',$where).' ORDER BY p.`dt` DESC,p.`id` DESC LIMIT 250';$s=tt_prepare($db,$sql);if($types!=='')$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();if($q!==''){foreach($rows as &$r)$r['_score']=tt_tag_relevance($q,(string)$r['tags']);unset($r);usort($rows,fn($a,$b)=>(($b['_score']<=>$a['_score'])?:strcmp((string)$b['dt'],(string)$a['dt'])));} $rows=array_slice($rows,0,100);
// One rating read for the visible result set. The creator's own vote is weighted
// one-to-one against all external votes on that post, per the original README.
$ratingState=[];$ownerByPost=[];foreach($rows as $r)$ownerByPost[(int)$r['id']]=(int)($r['owner_account_id']??0);if($rows){$ids=implode(',',array_map(fn($r)=>(int)$r['id'],$rows));$rr=$db->query('SELECT `post_id`,`voter_account_id`,`perspective` FROM `post_ratings` WHERE `post_id` IN ('.$ids.')');while($rr&&($x=$rr->fetch_assoc())){$pid=(int)$x['post_id'];$voter=(int)$x['voter_account_id'];$pv=tt_perspective_normalized((int)$x['perspective']);if(!isset($ratingState[$pid]))$ratingState[$pid]=['ext_n'=>0,'ext_sum'=>0.0,'owner'=>null,'count'=>0,'mine'=>0];$ratingState[$pid]['count']++;if($voter===$uid)$ratingState[$pid]['mine']=(int)$x['perspective'];if($voter===($ownerByPost[$pid]??0))$ratingState[$pid]['owner']=$pv;else{$ratingState[$pid]['ext_n']++;$ratingState[$pid]['ext_sum']+=$pv;}}if($rr)$rr->free();}
foreach($rows as &$r){$pid=(int)$r['id'];$x=$ratingState[$pid]??['ext_n'=>0,'ext_sum'=>0.0,'owner'=>null,'count'=>0,'mine'=>0];$w=$x['ext_n'];$sum=$x['ext_sum'];if($x['owner']!==null){$ow=max(1,$x['ext_n']);$w+=$ow;$sum+=$x['owner']*$ow;}$r['_rating']=$w>0?(int)round(max(-1,min(1,$sum/$w))*256):0;$r['_rating_count']=$x['count'];$r['_my_rating']=$x['mine'];}unset($r);$replyAffinity=tt_reply_affinity_for_view($view,$scope==='all');$rows=tt_sort_reply_threads($rows,$replyAffinity);$db->close();
?>
<!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Posts</title></head><body>
<?php if($logged): tt_nav('post.php'); else: ?><nav class="navtop"><div><h1><a href="/">TABLETIME</a></h1><a href="post.php">Posts</a><a href="tags.php">Tags</a><a href="extend.php">Extend</a><a href="login.php">Login</a><a href="register.php">Register</a></div></nav><?php endif;?>
<main class="content"><?php if(isset($_GET['posted'])):?><p class="notice ok">Post #<?=(int)$_GET['posted']?> published and indexed.</p><?php endif;?><?php if(isset($_GET['rated'])):?><p class="notice ok">Karma/Moksha perspective saved.</p><?php endif;?><?php if(isset($_GET['deleted'])):?><p class="notice ok">Post deleted; its ratings were removed too, so its delay contribution is gone.</p><?php endif;?>
<form method="get" class="searchbar scope-search"><input name="q" value="<?=tt_h($q)?>" placeholder="Search text or tags"><div class="scope-control"><label for="post-scope-view">Scope: <output id="post-scope-label"><?=tt_h($scope==='all'?'all':$scope)?></output></label><input class="scope-slider" id="post-scope-view" name="view" type="range" min="-256" max="256" step="1" value="<?=$scope==='all'?0:tt_scope_slider_value($scope)?>"><div class="slider-labels"><span>private</span><span>public</span><span>global</span></div><label class="inline-check"><input type="checkbox" name="all_scopes" id="all-scopes" value="1" <?=$scope==='all'?'checked':''?>> all visible scopes</label></div><select name="type"><option value="all">all types</option><?php foreach(['post','media','message','event','group','forum'] as $t):?><option value="<?=$t?>" <?=$type===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select><button>Search</button></form>
<p class="meta"><?=count($rows)?> matching posts. Historical scope math is preserved: slider/256 maps ≤ −0.5 private, middle public, ≥ +0.5 global. Reply-chain affinity is <?=number_format($replyAffinity*100,0)?>%: it increases continuously toward global scope so posts connected by <code>ID#:&lt;post-id&gt;</code> stay increasingly close together.</p>
<section class="grid"><?php foreach($rows as $r):?><article class="card post-card" id="post-<?=(int)$r['id']?>" data-post-expandable="1" aria-expanded="false"><h2><?=tt_h($r['title'])?></h2><p class="meta">#<?=(int)$r['id']?> · <?=tt_h($r['name'])?> · <?=tt_h($r['dt'])?> · <?=tt_h(trim($r['scope']))?> · <?=tt_h($r['type'])?><?=$r['federated']?' · federated':''?><?php if(isset($r['_score'])):?> · tag score <?=number_format((float)$r['_score'],3)?><?php endif;?><?php if((int)($r['_reply_parent']??0)>0):?> · reply to #<?=(int)$r['_reply_parent']?><?php endif;?></p><p><?=nl2br(tt_h($r['content']))?></p><?php if($r['file']!==''):?><p><a href="<?=tt_h($r['file'])?>" rel="noopener">Attachment</a></p><?php endif;?><div><?php foreach(tt_parse_tags((string)$r['tags']) as $tag):?><a class="tag" href="?q=<?=rawurlencode($tag['raw'])?>"><?=tt_h($tag['raw'])?></a><?php endforeach;?></div><?php if(trim((string)$r['comments'])!==''):?><details class="comments-disclosure"><summary>Comments</summary><pre class="comments-body"><?=tt_h($r['comments'])?></pre></details><?php endif;?>
<div class="karma-summary"><strong>Karma/Moksha:</strong> <?=((int)$r['_rating']>=0?'+':'').(int)$r['_rating']?> / 256 · <?=(int)$r['_rating_count']?> rating<?=((int)$r['_rating_count']===1?'':'s')?></div>
<?php if($logged && (int)$r['owner_account_id']>0):?><form method="post" action="rate.php" class="rating-form"><input type="hidden" name="post_id" value="<?=(int)$r['id']?>"><label for="rate-<?=(int)$r['id']?>"><?=hash_equals($user,(string)$r['name'])?'Moksha / creator perspective (one-to-one against external ratings)':'Karma / Moksha perspective'?>: <output id="rate-out-<?=(int)$r['id']?>"><?=(int)$r['_my_rating']?></output></label><input class="karma-slider" id="rate-<?=(int)$r['id']?>" type="range" name="perspective" min="-256" max="256" step="1" value="<?=(int)$r['_my_rating']?>" oninput="document.getElementById('rate-out-<?=(int)$r['id']?>').value=this.value"><div class="slider-labels"><span>−256 bad / voteban edge</span><span>0</span><span>+256 good</span></div><button type="submit">Set perspective</button></form><?php endif;?>
<?php if($logged):?><?php $targetUser=tt_reply_target_user((string)$r['name'],(string)$r['recipients'],$user);$replyMode=tt_reply_mode_for_post_type((string)$r['type']);?><div class="actions"><a href="<?=tt_h(tt_compose_url('comment',(int)$r['id'],(string)$r['name'],(string)$r['type'],(string)$r['title'],trim((string)$r['scope']),$targetUser))?>">Comment</a><a href="<?=tt_h(tt_compose_url('reply',(int)$r['id'],(string)$r['name'],(string)$r['type'],(string)$r['title'],trim((string)$r['scope']),$targetUser))?>">Reply as <?=tt_h($replyMode)?></a><?php if(hash_equals($user,(string)$r['name'])):?><form method="post" action="delete.php" class="inline-form"><input type="hidden" name="post_id" value="<?=(int)$r['id']?>"><button type="submit" onclick="return confirm('Delete this post? Its ratings and their delay contribution will also be removed.')">Delete</button></form><?php endif;?></div><?php endif;?></article><?php endforeach;?><?php if(!$rows):?><article class="card"><h2>No posts matched</h2><p>Try a broader search or publish a post.</p></article><?php endif;?></section></main>

<script>const sv=document.getElementById('post-scope-view'),sl=document.getElementById('post-scope-label'),all=document.getElementById('all-scopes');function sn(v){v=Number(v)/256;return v<=-.5?'private':(v>=.5?'global':'public')}if(sv){sv.addEventListener('input',()=>{all.checked=false;sl.value=sn(sv.value);sl.textContent=sn(sv.value)});all.addEventListener('change',()=>{sl.value=all.checked?'all':sn(sv.value);sl.textContent=sl.value})}</script>
</body></html>
