<?php
/** Additive, idempotent compatibility migrations for legacy Tabletime databases. */
function tt_schema_table_exists(mysqli $db,string $table):bool{$s=$db->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');if(!$s)return false;$s->bind_param('s',$table);if(!$s->execute()){$s->close();return false;}$s->bind_result($n);$s->fetch();$s->close();return (int)$n>0;}
function tt_schema_column_exists(mysqli $db,string $table,string $column):bool{$s=$db->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?');if(!$s)return false;$s->bind_param('ss',$table,$column);if(!$s->execute()){$s->close();return false;}$s->bind_result($n);$s->fetch();$s->close();return (int)$n>0;}
function tt_schema_add_column(mysqli $db,string $table,string $column,string $definition,array &$notes):bool{if(tt_schema_column_exists($db,$table,$column))return true;$sql='ALTER TABLE `'.$table.'` ADD `'.$column.'` '.$definition;if(!$db->query($sql))return false;$notes[]='added '.$table.'.'.$column;return true;}
function tt_schema_index_exists(mysqli $db,string $table,string $index):bool{$s=$db->prepare('SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name=? AND index_name=?');if(!$s)return false;$s->bind_param('ss',$table,$index);if(!$s->execute()){$s->close();return false;}$s->bind_result($n);$s->fetch();$s->close();return (int)$n>0;}
function tt_schema_add_index(mysqli $db,string $table,string $index,string $sql,array &$notes):bool{if(tt_schema_index_exists($db,$table,$index))return true;if(!$db->query($sql))return false;$notes[]='added index '.$table.'.'.$index;return true;}
function tt_schema_create_tables(mysqli $db,array &$notes):bool{
 $sqls=[
 "CREATE TABLE IF NOT EXISTS `accounts` (`id` int unsigned NOT NULL AUTO_INCREMENT,`username` varchar(50) NOT NULL DEFAULT '',`password` varchar(255) NOT NULL DEFAULT '',`email` varchar(100) NOT NULL DEFAULT '',`friends` longtext NULL,`posts` longtext NULL,`groups` longtext NULL,`events` longtext NULL,`forums` longtext NULL,`tags` longtext NULL,`messages` longtext NULL,`colors` longtext NULL,`votes` longtext NULL,`files` longtext NULL,`hostips` longtext NULL,`hostmode` int NOT NULL DEFAULT 0,`aboutcontent` longtext NULL,`delay` time NOT NULL DEFAULT '00:00:00',`ip` varchar(255) NOT NULL DEFAULT '',`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`last_login_at` datetime DEFAULT NULL,`protected_account` tinyint(1) NOT NULL DEFAULT 0,PRIMARY KEY(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `posts` (`id` int unsigned NOT NULL AUTO_INCREMENT,`title` varchar(255) NOT NULL DEFAULT '',`content` longtext NULL,`dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`file` varchar(1024) NOT NULL DEFAULT '',`tags` longtext NULL,`name` varchar(50) NOT NULL DEFAULT '',`comments` longtext NULL,`scope` varchar(32) NOT NULL DEFAULT 'public',`recipients` longtext NULL,`type` varchar(32) NOT NULL DEFAULT 'post',`votes` longtext NULL,`pinned` tinyint(1) NOT NULL DEFAULT 0,`origin_host` varchar(255) DEFAULT NULL,`origin_post_id` varchar(64) DEFAULT NULL,`origin_created_at` datetime DEFAULT NULL,`federated` tinyint(1) NOT NULL DEFAULT 0,PRIMARY KEY(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `events` (`id` int unsigned NOT NULL AUTO_INCREMENT,`title` varchar(255) NOT NULL DEFAULT '',`members` longtext NULL,`about` longtext NULL,`groups` longtext NULL,`posts` longtext NULL,`tags` longtext NULL,`type` varchar(64) NOT NULL DEFAULT 'event',PRIMARY KEY(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `groups` (`id` int unsigned NOT NULL AUTO_INCREMENT,`title` varchar(255) NOT NULL DEFAULT '',`about` longtext NULL,`members` longtext NULL,`forums` longtext NULL,`events` longtext NULL,`posts` longtext NULL,`tags` longtext NULL,PRIMARY KEY(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `forums` (`id` int unsigned NOT NULL AUTO_INCREMENT,`tag` varchar(191) NOT NULL DEFAULT '',`posts` longtext NULL,`groups` longtext NULL,`events` longtext NULL,PRIMARY KEY(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `tags` (`value` varchar(191) NOT NULL,`posts` longtext NULL,`forums` longtext NULL,`events` longtext NULL,`groups` longtext NULL,PRIMARY KEY(`value`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `post_attachments` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`post_id` int unsigned NOT NULL,`filename` varchar(255) NOT NULL,`mime_type` varchar(191) NOT NULL DEFAULT 'application/octet-stream',`size_bytes` int unsigned NOT NULL DEFAULT 0,`data` mediumblob NOT NULL,`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `uq_post_attachments_post`(`post_id`),KEY `idx_post_attachments_created`(`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `post_tags` (`tag` varchar(191) NOT NULL,`post_id` int unsigned NOT NULL,PRIMARY KEY(`tag`,`post_id`),KEY `idx_post_tags_post_id`(`post_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `tag_index` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`post_id` int unsigned NOT NULL,`tag` varchar(191) NOT NULL,`raw_token` varchar(255) NOT NULL,`is_numeric` tinyint(1) NOT NULL DEFAULT 0,`polarity` tinyint NOT NULL DEFAULT 1,`comparator` varchar(2) NOT NULL DEFAULT '',`numeric_value` double DEFAULT NULL,`expression_text` varchar(191) NOT NULL DEFAULT '',PRIMARY KEY(`id`),KEY `idx_tag_index_tag`(`tag`),KEY `idx_tag_index_post`(`post_id`),KEY `idx_tag_index_numeric`(`tag`,`is_numeric`,`numeric_value`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `federation_peers` (`id` int unsigned NOT NULL AUTO_INCREMENT,`base_url` varchar(512) NOT NULL,`tier` varchar(16) NOT NULL DEFAULT 'host',`enabled` tinyint(1) NOT NULL DEFAULT 1,`cursor_at` datetime DEFAULT NULL,`last_sync_at` datetime DEFAULT NULL,`last_error` varchar(512) NOT NULL DEFAULT '',`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `uq_federation_peer_url`(`base_url`(191)),KEY `idx_federation_due`(`enabled`,`last_sync_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `federation_tombstones` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`origin_host` varchar(255) DEFAULT NULL,`origin_post_id` varchar(64) NOT NULL,`deleted_at` datetime NOT NULL,PRIMARY KEY(`id`),KEY `idx_tombstone_deleted`(`deleted_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `node_settings` (`setting_key` varchar(100) NOT NULL,`setting_value` varchar(2048) NOT NULL,PRIMARY KEY(`setting_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `auth_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`account_id` int unsigned NOT NULL,`selector` char(24) NOT NULL,`token_hash` char(64) NOT NULL,`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`last_used_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`revoked_at` datetime DEFAULT NULL,PRIMARY KEY(`id`),UNIQUE KEY `uq_auth_selector`(`selector`),KEY `idx_auth_account`(`account_id`,`revoked_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `calls` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`call_key` char(32) NOT NULL,`scope_type` varchar(16) NOT NULL DEFAULT 'private',`scope_id` int unsigned DEFAULT NULL,`created_by` int unsigned NOT NULL,`title` varchar(255) NOT NULL DEFAULT '',`members` longtext NULL,`status` varchar(16) NOT NULL DEFAULT 'open',`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `uq_calls_key`(`call_key`),KEY `idx_calls_scope`(`scope_type`,`scope_id`,`status`),KEY `idx_calls_updated`(`updated_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `call_participants` (`call_id` bigint unsigned NOT NULL,`account_id` int unsigned NOT NULL,`username` varchar(50) NOT NULL DEFAULT '',`joined_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`last_seen_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`left_at` datetime DEFAULT NULL,PRIMARY KEY(`call_id`,`account_id`),KEY `idx_call_participants_seen`(`call_id`,`left_at`,`last_seen_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `call_signals` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`call_id` bigint unsigned NOT NULL,`from_account_id` int unsigned NOT NULL,`to_account_id` int unsigned DEFAULT NULL,`signal_type` varchar(24) NOT NULL,`payload` mediumtext NOT NULL,`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_call_signal_poll`(`call_id`,`to_account_id`,`id`),KEY `idx_call_signal_created`(`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS `notifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`account_id` int unsigned NOT NULL,`kind` varchar(32) NOT NULL DEFAULT 'activity',`title` varchar(255) NOT NULL DEFAULT '',`body` varchar(1000) NOT NULL DEFAULT '',`url` varchar(1024) NOT NULL DEFAULT '',`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`read_at` datetime DEFAULT NULL,PRIMARY KEY(`id`),KEY `idx_notifications_poll`(`account_id`,`read_at`,`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
 ];foreach($sqls as $sql){if(!$db->query($sql))return false;}$notes[]='runtime tables present';return true;
}
function tt_schema_upgrade_columns(mysqli $db,string $table,array $defs,array &$notes):bool{if(!tt_schema_table_exists($db,$table))return false;if(!tt_schema_column_exists($db,$table,'id')&&$table!=='tags')return false;foreach($defs as $c=>$d)if(!tt_schema_add_column($db,$table,$c,$d,$notes))return false;return true;}
function tt_upgrade_accounts_schema(mysqli $db,array &$notes=[]):bool{
 $defs=['username'=>"varchar(50) NOT NULL DEFAULT ''",'password'=>"varchar(255) NOT NULL DEFAULT ''",'email'=>"varchar(100) NOT NULL DEFAULT ''",'friends'=>'longtext NULL','posts'=>'longtext NULL','groups'=>'longtext NULL','events'=>'longtext NULL','forums'=>'longtext NULL','tags'=>'longtext NULL','messages'=>'longtext NULL','colors'=>'longtext NULL','votes'=>'longtext NULL','files'=>'longtext NULL','hostips'=>'longtext NULL','hostmode'=>'int NOT NULL DEFAULT 0','aboutcontent'=>'longtext NULL','delay'=>"time NOT NULL DEFAULT '00:00:00'",'ip'=>"varchar(255) NOT NULL DEFAULT ''",'created_at'=>'datetime NOT NULL DEFAULT CURRENT_TIMESTAMP','last_login_at'=>'datetime DEFAULT NULL','protected_account'=>'tinyint(1) NOT NULL DEFAULT 0'];if(!tt_schema_upgrade_columns($db,'accounts',$defs,$notes))return false;
 if(!tt_schema_index_exists($db,'accounts','uq_accounts_username')){$dupes=$db->query("SELECT `username` FROM `accounts` WHERE `username`<>'' GROUP BY `username` HAVING COUNT(*)>1 LIMIT 1");$has=$dupes&&$dupes->num_rows>0;if($dupes)$dupes->free();if(!$has)$db->query('CREATE UNIQUE INDEX `uq_accounts_username` ON `accounts` (`username`)');}
 if(!tt_schema_index_exists($db,'accounts','idx_accounts_hostmode'))$db->query('CREATE INDEX `idx_accounts_hostmode` ON `accounts` (`hostmode`)');return true;
}
function tt_upgrade_posts_schema(mysqli $db,array &$notes=[]):bool{$defs=['title'=>"varchar(255) NOT NULL DEFAULT ''",'content'=>'longtext NULL','dt'=>'datetime NULL','file'=>"varchar(1024) NOT NULL DEFAULT ''",'tags'=>'longtext NULL','name'=>"varchar(50) NOT NULL DEFAULT ''",'comments'=>'longtext NULL','scope'=>"varchar(32) NOT NULL DEFAULT 'public'",'recipients'=>'longtext NULL','type'=>"varchar(32) NOT NULL DEFAULT 'post'",'votes'=>'longtext NULL','pinned'=>'tinyint(1) NOT NULL DEFAULT 0','origin_host'=>'varchar(255) DEFAULT NULL','origin_post_id'=>'varchar(64) DEFAULT NULL','origin_created_at'=>'datetime DEFAULT NULL','federated'=>'tinyint(1) NOT NULL DEFAULT 0'];return tt_schema_upgrade_columns($db,'posts',$defs,$notes);}
function tt_upgrade_events_schema(mysqli $db,array &$notes=[]):bool{return tt_schema_upgrade_columns($db,'events',['title'=>"varchar(255) NOT NULL DEFAULT ''",'members'=>'longtext NULL','about'=>'longtext NULL','groups'=>'longtext NULL','posts'=>'longtext NULL','tags'=>'longtext NULL','type'=>"varchar(64) NOT NULL DEFAULT 'event'"],$notes);}
function tt_upgrade_groups_schema(mysqli $db,array &$notes=[]):bool{return tt_schema_upgrade_columns($db,'groups',['title'=>"varchar(255) NOT NULL DEFAULT ''",'about'=>'longtext NULL','members'=>'longtext NULL','forums'=>'longtext NULL','events'=>'longtext NULL','posts'=>'longtext NULL','tags'=>'longtext NULL'],$notes);}
function tt_upgrade_forums_schema(mysqli $db,array &$notes=[]):bool{return tt_schema_upgrade_columns($db,'forums',['tag'=>"varchar(191) NOT NULL DEFAULT ''",'posts'=>'longtext NULL','groups'=>'longtext NULL','events'=>'longtext NULL'],$notes);}
function tt_upgrade_runtime_schema(mysqli $db,array &$notes=[]):bool{if(!tt_schema_create_tables($db,$notes))return false;if(!tt_upgrade_accounts_schema($db,$notes)||!tt_upgrade_posts_schema($db,$notes)||!tt_upgrade_events_schema($db,$notes)||!tt_upgrade_groups_schema($db,$notes)||!tt_upgrade_forums_schema($db,$notes))return false;
 $indexes=[['posts','idx_posts_dt','CREATE INDEX `idx_posts_dt` ON `posts` (`dt`)'],['posts','idx_posts_name','CREATE INDEX `idx_posts_name` ON `posts` (`name`)'],['posts','idx_posts_scope','CREATE INDEX `idx_posts_scope` ON `posts` (`scope`)'],['posts','idx_posts_type','CREATE INDEX `idx_posts_type` ON `posts` (`type`)'],['posts','uq_posts_origin','CREATE UNIQUE INDEX `uq_posts_origin` ON `posts` (`origin_host`,`origin_post_id`)'],['groups','idx_groups_title','CREATE INDEX `idx_groups_title` ON `groups` (`title`)'],['events','idx_events_title','CREATE INDEX `idx_events_title` ON `events` (`title`)']];foreach($indexes as [$t,$i,$sql]){if(!tt_schema_index_exists($db,$t,$i))@$db->query($sql);}if(!tt_schema_index_exists($db,'forums','uq_forums_tag'))@$db->query('CREATE UNIQUE INDEX `uq_forums_tag` ON `forums` (`tag`)');return true;}
function tt_verify_accounts_runtime_columns(mysqli $db):array{$needed=['id','username','password','email','friends','posts','groups','events','forums','tags','messages','colors','votes','files','hostips','hostmode','aboutcontent','delay','ip','created_at','last_login_at','protected_account'];$missing=[];foreach($needed as $c)if(!tt_schema_column_exists($db,'accounts',$c))$missing[]=$c;return $missing;}
function tt_runtime_sql_selfcheck(mysqli $db):array{$sqls=[
 'register'=>'INSERT INTO `accounts` (`username`,`password`,`email`,`friends`,`posts`,`groups`,`events`,`forums`,`tags`,`messages`,`colors`,`votes`,`files`,`hostips`,`hostmode`,`aboutcontent`,`delay`,`ip`,`created_at`,`last_login_at`,`protected_account`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP(),?)',
 'login'=>'SELECT `id`,`username`,`password`,`email`,`friends`,`posts`,`groups`,`events`,`colors`,`votes`,`forums`,`tags`,`aboutcontent`,`files` FROM `accounts` WHERE `username`=? LIMIT 1',
 'post'=>'INSERT INTO `posts` (`title`,`content`,`dt`,`file`,`tags`,`name`,`comments`,`scope`,`recipients`,`type`,`votes`,`pinned`,`federated`) VALUES (?,?,?,?,?,?,?,?,?,?,?,0,0)',
 'event'=>'INSERT INTO `events` (`title`,`members`,`about`,`groups`,`posts`,`tags`,`type`) VALUES (?,?,?,?,?,?,?)',
 'group'=>'INSERT INTO `groups` (`title`,`members`,`about`,`forums`,`events`,`posts`,`tags`) VALUES (?,?,?,?,?,?,?)',
 'forum'=>'INSERT INTO `forums` (`tag`,`posts`,`groups`,`events`) VALUES (?,?,?,?)',
 'attachment'=>'INSERT INTO `post_attachments` (`post_id`,`filename`,`mime_type`,`size_bytes`,`data`) VALUES (?,?,?,?,?)',
 'messages'=>"SELECT `id`,`title`,`content`,`dt`,`tags`,`name`,`recipients`,`file` FROM `posts` WHERE `type`='message' AND (`name`=? OR `recipients`=?) LIMIT 1"
 ];$fail=[];foreach($sqls as $name=>$sql){$s=$db->prepare($sql);if(!$s)$fail[$name]=$db->error;else$s->close();}return $fail;}

function tt_runtime_write_selfcheck(mysqli $db):array{
 $token='__tt_selftest_'.bin2hex(random_bytes(6));$accountId=0;$postId=0;$groupId=0;$eventId=0;$forumId=0;$errors=[];
 try{
  $db->begin_transaction();$empty='';$hash=password_hash('tabletime-selftest',PASSWORD_DEFAULT)?:'x';$email=$token.'@example.invalid';$hostmode=0;$delay='00:00:00';$ip='127.0.0.1';$protected=0;
  $sql='INSERT INTO `accounts` (`username`,`password`,`email`,`friends`,`posts`,`groups`,`events`,`forums`,`tags`,`messages`,`colors`,`votes`,`files`,`hostips`,`hostmode`,`aboutcontent`,`delay`,`ip`,`created_at`,`last_login_at`,`protected_account`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP(),?)';$st=$db->prepare($sql);if(!$st)throw new RuntimeException('register prepare: '.$db->error);$st->bind_param('ssssssssssssssisssi',$token,$hash,$email,$empty,$empty,$empty,$empty,$empty,$empty,$empty,$empty,$empty,$empty,$empty,$hostmode,$empty,$delay,$ip,$protected);if(!$st->execute())throw new RuntimeException('register execute: '.$st->error);$accountId=(int)$db->insert_id;$st->close();
  $title=$token;$content='self-test';$dt=gmdate('Y-m-d H:i:s');$file='';$tags='selftest=1';$name=$token;$comments='';$scope='public';$recipients='';$type='post';$votes='';$st=$db->prepare('INSERT INTO `posts` (`title`,`content`,`dt`,`file`,`tags`,`name`,`comments`,`scope`,`recipients`,`type`,`votes`,`pinned`,`federated`) VALUES (?,?,?,?,?,?,?,?,?,?,?,0,0)');if(!$st)throw new RuntimeException('post prepare: '.$db->error);$st->bind_param('sssssssssss',$title,$content,$dt,$file,$tags,$name,$comments,$scope,$recipients,$type,$votes);if(!$st->execute())throw new RuntimeException('post execute: '.$st->error);$postId=(int)$db->insert_id;$st->close();
  $filename='selftest.txt';$mime='text/plain';$size=8;$data='selftest';$st=$db->prepare('INSERT INTO `post_attachments` (`post_id`,`filename`,`mime_type`,`size_bytes`,`data`) VALUES (?,?,?,?,?)');if(!$st)throw new RuntimeException('attachment prepare: '.$db->error);$st->bind_param('issis',$postId,$filename,$mime,$size,$data);if(!$st->execute())throw new RuntimeException('attachment execute: '.$st->error);$st->close();
  $members=$token;$about='self-test';$groups='';$posts='';$etype='event';$st=$db->prepare('INSERT INTO `events` (`title`,`members`,`about`,`groups`,`posts`,`tags`,`type`) VALUES (?,?,?,?,?,?,?)');if(!$st)throw new RuntimeException('event prepare: '.$db->error);$st->bind_param('sssssss',$title,$members,$about,$groups,$posts,$tags,$etype);if(!$st->execute())throw new RuntimeException('event execute: '.$st->error);$eventId=(int)$db->insert_id;$st->close();
  $forums='';$events='';$st=$db->prepare('INSERT INTO `groups` (`title`,`members`,`about`,`forums`,`events`,`posts`,`tags`) VALUES (?,?,?,?,?,?,?)');if(!$st)throw new RuntimeException('group prepare: '.$db->error);$st->bind_param('sssssss',$title,$members,$about,$forums,$events,$posts,$tags);if(!$st->execute())throw new RuntimeException('group execute: '.$st->error);$groupId=(int)$db->insert_id;$st->close();
  $st=$db->prepare('INSERT INTO `forums` (`tag`,`posts`,`groups`,`events`) VALUES (?,?,?,?)');if(!$st)throw new RuntimeException('forum prepare: '.$db->error);$st->bind_param('ssss',$token,$posts,$groups,$events);if(!$st->execute())throw new RuntimeException('forum execute: '.$st->error);$forumId=(int)$db->insert_id;$st->close();
  $st=$db->prepare('SELECT COUNT(*) FROM `accounts` a JOIN `posts` p ON p.`name`=a.`username` WHERE a.`id`=? AND p.`id`=?');$st->bind_param('ii',$accountId,$postId);$st->execute();$st->bind_result($n);$st->fetch();$st->close();if((int)$n!==1)throw new RuntimeException('write/read verification returned no row');
 }catch(Throwable $e){$errors[]=$e->getMessage();}
 @ $db->rollback();
 // Cleanup is also issued explicitly for legacy non-transactional tables.
 if($postId){@$db->query('DELETE FROM `post_attachments` WHERE `post_id`='.(int)$postId);@$db->query('DELETE FROM `post_tags` WHERE `post_id`='.(int)$postId);@$db->query('DELETE FROM `tag_index` WHERE `post_id`='.(int)$postId);@$db->query('DELETE FROM `posts` WHERE `id`='.(int)$postId);}
 if($groupId)@$db->query('DELETE FROM `groups` WHERE `id`='.(int)$groupId);if($eventId)@$db->query('DELETE FROM `events` WHERE `id`='.(int)$eventId);if($forumId)@$db->query('DELETE FROM `forums` WHERE `id`='.(int)$forumId);if($accountId)@$db->query('DELETE FROM `accounts` WHERE `id`='.(int)$accountId);
 // Token cleanup is a second guard if a legacy table did not report insert_id normally.
 $esc=$db->real_escape_string($token);@$db->query("DELETE FROM `posts` WHERE `name`='$esc' AND `title`='$esc'");@$db->query("DELETE FROM `groups` WHERE `title`='$esc'");@$db->query("DELETE FROM `events` WHERE `title`='$esc'");@$db->query("DELETE FROM `forums` WHERE `tag`='$esc'");@$db->query("DELETE FROM `accounts` WHERE `username`='$esc'");
 return $errors;
}
?>
