<?php
require_once __DIR__.'/core.php';require_once __DIR__.'/square_lib.php';require_once __DIR__.'/payout_lib.php';tt_require_login();$db=tt_db_open(false);$uid=(int)$_SESSION['id'];$ready=tt_payout_schema_ready($db);$conn=$ready?tt_square_seller_connection($db,$uid):null;$db->close();
?><!doctype html><html class="tabletime"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.php"><title>Tabletime · Square setup</title></head><body><?php tt_nav('earnings.php');?><main class="content"><h2>Set up Square for Tabletime payments</h2>
<?php if(isset($_GET['connected'])):?><p class="notice ok">Square connected successfully.</p><?php endif;?><?php if(isset($_GET['denied'])):?><p class="notice error">Square connection was not approved. You can try again when ready.</p><?php endif;?>
<section class="card"><h3>What you need</h3><ol><li>Create or sign in to a Square seller account.</li><li>In Square, finish your business identity/profile information.</li><li>Link the bank account or eligible transfer destination where you want Square funds to settle.</li><li>Return here and choose <strong>Connect Square</strong>.</li><li>Sign in on Square's authorization screen and approve the requested permissions. Tabletime never asks you to paste your Square password, Application Secret, or access token into a profile field.</li><li>After Square sends you back to Tabletime, your Earnings page will show the connected merchant ID and let you submit payout requests against your available Tabletime cash balance.</li></ol><p class="meta">Tabletime requests only the Square permissions needed to identify the seller account and inspect linked payout/bank information. OAuth tokens are stored encrypted on the Tabletime server.</p></section>
<section class="card"><h3>Connection status</h3><?php if(!$ready):?><p class="notice">The Tabletime payout tables are not installed yet. The site operator must run protected schema maintenance once.</p><?php elseif($conn):?><p><strong>Connected.</strong> Merchant ID: <code><?=tt_h((string)$conn['merchant_id'])?></code></p><p class="meta">Environment: <?=tt_h((string)$conn['environment'])?> · scopes: <?=tt_h((string)$conn['scopes'])?> · updated <?=tt_h((string)$conn['updated_at'])?></p><p><a class="button-link" href="earnings.php">Return to Earnings</a></p><?php elseif(!tt_square_oauth_ready()):?><p class="notice">Square OAuth is not configured on this Tabletime host yet. The operator must set the Square OAuth application ID, application secret, redirect URL, and token-encryption key.</p><?php else:?><form method="post" action="square_oauth_start.php"><button type="submit">Connect Square</button></form><?php endif;?></section>
<section class="card"><h3>Important distinction</h3><p>Your Square seller account is your payment destination identity. Square's Payouts API reports Square payouts; it does not itself create arbitrary transfers from Tabletime's Square balance. Tabletime therefore records payout requests and their status/history, and can send them to the operator's configured payout-dispatch service. A request is not marked paid until the payout workflow confirms it.</p></section>
</main>
<!-- TABLETIME_NSFW_BLUR_20260915 -->
<script src="nsfw-blur.js?v=20260915c" defer></script>
</body></html>
