(()=>{if(!('serviceWorker'in navigator))return;let last=Number(localStorage.getItem('ttNotificationId')||0);navigator.serviceWorker.register('sw.js').catch(()=>{});async function poll(){if(document.visibilityState==='hidden'||document.visibilityState==='visible'){try{const r=await fetch('api/notifications.php?after='+last,{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const d=await r.json();for(const n of d.notifications||[]){last=Math.max(last,Number(n.id)||0);if(Notification.permission==='granted'){const reg=await navigator.serviceWorker.ready;reg.showNotification(n.title||'Tabletime',{body:n.body||'',tag:'tt-'+n.id,data:{url:n.url||'home.php'}});}}localStorage.setItem('ttNotificationId',String(last));}catch(_){}}}window.ttEnableNotifications=()=>Notification.requestPermission();if('Notification'in window&&Notification.permission==='default'){const b=document.createElement('button');b.textContent='Enable notifications';b.className='tt-notify-enable';b.onclick=()=>Notification.requestPermission().then(()=>b.remove());document.addEventListener('DOMContentLoaded',()=>document.body.appendChild(b),{once:true});}setInterval(poll,10000);setTimeout(poll,1200);})();
;(()=>{
  if(window.__ttPostCardExpandBooted)return;
  window.__ttPostCardExpandBooted=true;
  const interactive='a,button,input,select,textarea,label,summary,details,form,video,audio,iframe,object,embed,[contenteditable="true"],[role="button"]';
  document.addEventListener('click',e=>{
    const card=e.target.closest('.post-card[data-post-expandable="1"],.tt-expand-card[data-tt-expandable="1"]');
    if(!card||e.target.closest(interactive))return;
    const sel=window.getSelection&&window.getSelection();
    if(sel&&String(sel).trim()!=='')return;
    const expanded=card.classList.toggle('is-expanded');
    card.setAttribute('aria-expanded',expanded?'true':'false');
    if(expanded)card.scrollIntoView({behavior:'smooth',block:'nearest'});
  });
})();
;(()=>{if(window.__ttCallPresenceBooted)return;window.__ttCallPresenceBooted=true;let seen=new Set(),armed=false;addEventListener('pointerdown',()=>armed=true,{once:true,capture:true});function beep(){if(!armed)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=740;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.18);setTimeout(()=>a.close(),400);}catch(_){}}function dock(){let d=document.getElementById('tt-call-dock');if(!d){d=document.createElement('aside');d.id='tt-call-dock';d.className='tt-call-dock';document.body.appendChild(d);}return d;}function openCall(k){const u='calls.php?join='+encodeURIComponent(k)+'&callwindow=1',w=open(u,'ttcall-'+k,'popup=yes,width=900,height=720');if(!w)location.href=u;}async function poll(){if(!document.querySelector('.navtop a[href="calls.php"]'))return;try{const r=await fetch('api/call_presence.php',{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const d=await r.json(),n=Number(d.count)||0,c=document.getElementById('tt-call-count');if(c)c.textContent=n?` (${n} call${n===1?'':'s'})`:'';const incoming=(d.calls||[]).filter(x=>!x.joined);const box=dock();box.innerHTML=incoming.slice(0,3).map(x=>`<div><strong>Incoming ${String(x.scope_type).replace(/[<>&]/g,'')} call</strong><span>${String(x.title).replace(/[<>&]/g,'')}</span><button data-call="${x.call_key}">Answer</button></div>`).join('');box.hidden=!incoming.length;box.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>openCall(b.dataset.call));for(const x of incoming){if(!seen.has(x.call_key)){seen.add(x.call_key);beep();if('Notification'in window&&Notification.permission==='granted'){navigator.serviceWorker?.ready.then(reg=>reg.showNotification('Tabletime call',{body:x.title||'Incoming call',tag:'tt-call-'+x.call_key,data:{url:'calls.php?join='+x.call_key}})).catch(()=>{});}}}}catch(_){}}setTimeout(poll,600);setInterval(poll,4000);})();
